/**
 * PhysiClinic — Firestore 완전 시딩 스크립트
 * SQL physiclinic_schema_v2.sql 의 모든 정적 데이터 포함
 *
 * 사용법:
 *   1. npm install firebase-admin
 *   2. Firebase Console → 프로젝트 설정 → 서비스 계정 → 새 비공개 키 생성
 *      → serviceAccountKey.json 으로 저장 (이 파일과 같은 폴더)
 *   3. node seed.js
 *
 * 시딩 대상:
 *   ✅ units                    (4개)
 *   ✅ misconception_dimensions  (17개)
 *   ✅ misconceptions            (84개 — unit1 30개 + unit2 16개 + unit3 24개 + unit4 14개)
 *   ✅ misconception_sentences   (70개+)
 *   ✅ scoring_keywords          (40개+, unit1 전용)
 *   ✅ fci_fmce_items            (73개 — FMCE 43 + FCI 30, unit1 전용)
 *   ✅ item_misconception_map    (80개+, unit1 전용)
 *
 * 제외 (동적 데이터):
 *   ❌ users / assessments / learning_sessions / learning_logs
 */

const admin = require('firebase-admin');
const serviceAccount = require('./serviceAccountKey.json');

admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
const db = admin.firestore();

/* ============================================================
   1. UNITS
   ============================================================ */
const units = [
  { id:'1', name:'힘과 운동',   keywords:['관성','외력','뉴턴','등속','힘','가속도','마찰','운동','속도','알짜힘','합력'] },
  { id:'2', name:'에너지',      keywords:['운동에너지','퍼텐셜에너지','역학적에너지','보존','일','에너지'] },
  { id:'3', name:'전기와 자기', keywords:['전류','전압','자기장','전기력','저항','전기'] },
  { id:'4', name:'파동',        keywords:['간섭','회절','파장','진동수','굴절','광전효과','이중성','불확정성'] },
];

/* ============================================================
   2. MISCONCEPTION DIMENSIONS
   ============================================================ */
const dims = [
  { id:'1', code:'K',  name_ko:'운동학',      name_en:'Kinematics',        description:'위치, 속도, 가속도 개념 혼동' },
  { id:'2', code:'I',  name_ko:'임페투스',    name_en:'Impetus',            description:'운동을 유지하는 내재적 힘이 있다는 믿음' },
  { id:'3', code:'AF', name_ko:'능동적 힘',   name_en:'Active Force',       description:'힘은 능동적 물체만 가할 수 있다는 믿음' },
  { id:'4', code:'AR', name_ko:'작용-반작용', name_en:'Action/Reaction',    description:'뉴턴 3법칙 관련 오개념' },
  { id:'5', code:'CI', name_ko:'힘의 합성',   name_en:'Concatenation',      description:'힘의 합성 및 우선순위 오개념' },
  { id:'6', code:'G',  name_ko:'중력/저항',   name_en:'Gravity/Resistance', description:'중력, 공기저항 관련 오개념' },
  { id:'7', code:'ME', name_ko:'역학적 에너지 보존', name_en:'Mechanical Energy Conservation', description:'위치에너지·운동에너지 전환 및 보존 관련 오개념' },
  { id:'8', code:'WI', name_ko:'파동의 간섭',        name_en:'Wave Interference',              description:'음파 등 종파 간섭에서 진폭·위상 관련 오개념' },
  { id:'9',  code:'MD',  name_ko:'물질의 이중성',      name_en:'Matter Duality',                    description:'불확정성 원리 등 양자역학적 이중성 관련 오개념' },
  { id:'10', code:'EC',  name_ko:'전기 회로',          name_en:'Electric Circuit',                  description:'전류·전압·저항 개념 혼동 및 회로 분석 오류' },
  { id:'11', code:'MF',  name_ko:'자기장',              name_en:'Magnetic Field',                    description:'직선 도선·코일 주변 자기장 방향·세기 오개념' },
  { id:'12', code:'EMI', name_ko:'전자기 유도',          name_en:'Electromagnetic Induction',         description:'유도 전류 발생 조건 및 렌츠 법칙 오개념' },
  { id:'13', code:'MO',  name_ko:'운동량',              name_en:'Momentum',                          description:'운동량 보존 및 충돌 상황 오개념' },
  { id:'14', code:'AT',  name_ko:'원자 모형',            name_en:'Atomic Model',                      description:'보어 모형·오비탈·에너지 준위 오개념' },
  { id:'15', code:'EB',  name_ko:'에너지 띠',            name_en:'Energy Band',                       description:'에너지 띠·반도체 원리 오개념' },
  { id:'16', code:'LD',  name_ko:'빛의 이중성',          name_en:'Light Duality',                     description:'광전효과·물질파·입자-파동 이중성 오개념' },
  { id:'17', code:'WR',  name_ko:'파동·굴절',            name_en:'Wave Refraction',                   description:'빛의 굴절·전반사·파장 변화 오개념' },
];

/* ============================================================
   3. MISCONCEPTIONS  (unit1: FCI Table 4-2 28개 / unit2,4: 논문 기반 19개)
   ============================================================ */
const misconceptions = [
  // Kinematics
  { id:'K1', unitId:'1', subUnit:'물체의 운동', subUnit:'물체의 운동', dimensionCode:'K', code:'K1', name_ko:'위치-속도 미분화', name_en:'Position-velocity undiscriminated',
    description:'위치와 속도를 동일하거나 유사한 개념으로 혼동함',
    correctConcept:'위치는 공간상 좌표, 속도는 위치 변화율로 서로 독립적인 물리량',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'K2', unitId:'1', subUnit:'물체의 운동', dimensionCode:'K', code:'K2', name_ko:'속도-가속도 미분화', name_en:'Velocity-acceleration undiscriminated',
    description:'속도와 가속도를 동일하거나 유사한 개념으로 혼동함',
    correctConcept:'가속도는 속도의 변화율이며 속도와 방향이 다를 수 있음',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'K3', unitId:'1', subUnit:'물체의 운동', dimensionCode:'K', code:'K3', name_ko:'비벡터적 속도 합성', name_en:'Nonvectorial velocity composition',
    description:'속도를 벡터가 아닌 스칼라로 합성함',
    correctConcept:'속도는 벡터량으로 방향을 고려한 벡터 합산이 필요함',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  // Impetus
  { id:'I1', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'I', code:'I1', name_ko:'충격에 의한 임페투스', name_en:'Impetus supplied by hit',
    description:'물체를 치면 운동을 유지시키는 힘(임페투스)이 전달된다고 믿음',
    correctConcept:'충격은 순간적인 힘을 가할 뿐, 운동을 유지시키는 내재적 힘은 존재하지 않음',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'I2', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'I', code:'I2', name_ko:'임페투스 소멸/회복', name_en:'Loss/recovery of original impetus',
    description:'물체가 방향을 바꿀 때 원래 임페투스가 소멸했다가 회복된다고 믿음',
    correctConcept:'힘은 가속도를 만들 뿐이며, 임페투스 같은 내재적 운동 유지력은 없음',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'I3', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'I', code:'I3', name_ko:'추진력 소진 이론', name_en:'Impetus dissipation',
    description:'운동하는 물체의 힘(임페투스)이 점차 소진되어 결국 정지한다고 믿음',
    correctConcept:'마찰이 없으면 외력 없이도 등속 운동이 지속됨 (뉴턴 제1법칙)',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'I4', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'I', code:'I4', name_ko:'임페투스 점진적 축적', name_en:'Gradual/delayed impetus build-up',
    description:'힘을 가해도 임페투스가 서서히 축적되어 가속이 지연된다고 믿음',
    correctConcept:'힘이 작용하는 순간부터 즉시 가속도가 발생함 (F=ma)',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'I5', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'I', code:'I5', name_ko:'원형 임페투스', name_en:'Circular impetus',
    description:'원형 경로를 따라 운동하던 물체가 경로를 벗어나도 원형 궤적을 유지한다고 믿음',
    correctConcept:'구속력이 사라지면 물체는 그 순간의 접선 방향으로 직선 운동함',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  // Active Force
  { id:'AF1', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'AF', code:'AF1', name_ko:'능동적 물체만 힘을 가함', name_en:'Only active agents exert forces',
    description:'생물이나 엔진 같은 능동적 물체만 힘을 가할 수 있다고 믿음',
    correctConcept:'정지한 물체(벽, 바닥 등)도 접촉한 물체에 힘(수직항력 등)을 가함',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'AF2', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'AF', code:'AF2', name_ko:'운동은 능동적 힘을 의미', name_en:'Motion implies active force',
    description:'물체가 운동하고 있으면 반드시 능동적 힘이 작용하고 있다고 믿음',
    correctConcept:'등속 운동은 알짜힘이 0인 상태이며 능동적 힘 없이도 유지됨',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'AF3', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'AF', code:'AF3', name_ko:'정지=힘 없음', name_en:'No motion implies no force',
    description:'물체가 정지해 있으면 어떤 힘도 작용하지 않는다고 믿음',
    correctConcept:'정지 물체에도 중력, 수직항력 등 여러 힘이 작용하며 알짜힘이 0인 것임',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'AF4', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'AF', code:'AF4', name_ko:'속도는 힘에 비례', name_en:'Velocity proportional to applied force',
    description:'물체의 속도가 작용하는 힘의 크기에 비례한다고 믿음',
    correctConcept:'힘은 가속도에 비례하며(F=ma), 속도가 아닌 속도 변화율에 비례함',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'AF5', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'AF', code:'AF5', name_ko:'가속도=힘 증가', name_en:'Acceleration implies increasing force',
    description:'물체가 가속 중이면 힘도 계속 증가한다고 믿음',
    correctConcept:'일정한 힘(F=const)이 작용하면 일정한 가속도가 발생함',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'AF6', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'AF', code:'AF6', name_ko:'힘은 종단속도까지 가속', name_en:'Force causes acceleration to terminal velocity',
    description:'힘이 작용하면 물체는 어느 최대 속도(종단속도)까지만 가속된다고 믿음',
    correctConcept:'마찰 없이 일정한 힘이 지속되면 속도는 계속 증가함',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'AF7', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'AF', code:'AF7', name_ko:'능동적 힘 소진', name_en:'Active force wears out',
    description:'엔진 등 능동 물체의 힘은 시간이 지남에 따라 소진된다고 믿음',
    correctConcept:'연료가 일정하면 엔진의 힘은 소진되지 않음',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  // Action/Reaction
  { id:'AR1', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'AR', code:'AR1', name_ko:'질량이 크면 힘이 큼', name_en:'Greater mass implies greater force',
    description:'충돌 시 질량이 더 큰 물체가 더 큰 힘을 가한다고 믿음',
    correctConcept:'뉴턴 제3법칙: 작용-반작용 힘의 크기는 항상 같음',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'AR2', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'AR', code:'AR2', name_ko:'능동적 물체가 더 큰 힘', name_en:'Most active agent produces greatest force',
    description:'더 능동적인 물체(움직이는 물체 등)가 더 큰 힘을 가한다고 믿음',
    correctConcept:'뉴턴 제3법칙: 능동성과 관계없이 작용-반작용 힘은 크기가 같음',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  // Concatenation
  { id:'CI1', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'CI', code:'CI1', name_ko:'가장 큰 힘이 운동 결정', name_en:'Largest force determines motion',
    description:'여러 힘 중 가장 큰 힘의 방향으로만 운동한다고 믿음',
    correctConcept:'운동은 모든 힘의 벡터 합(알짜힘)에 의해 결정됨',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'CI2', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'CI', code:'CI2', name_ko:'힘의 타협', name_en:'Force compromise determines motion',
    description:'여러 힘이 작용할 때 운동은 힘들 사이의 타협 방향으로 결정된다고 믿음',
    correctConcept:'운동은 모든 힘의 벡터 합에 의해 결정됨',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'CI3', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'CI', code:'CI3', name_ko:'마지막 힘이 운동 결정', name_en:'Last force to act determines motion',
    description:'가장 최근에 작용한 힘이 이후 운동 방향을 결정한다고 믿음',
    correctConcept:'운동은 현재 작용하는 모든 힘의 합에 의해 결정됨',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  // Gravity/Resistance
  { id:'CF', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'G', code:'CF', name_ko:'원심력 실재', name_en:'Centrifugal force',
    description:'원운동하는 물체에 바깥쪽으로 실제 힘(원심력)이 작용한다고 믿음',
    correctConcept:'원심력은 관성계에서는 존재하지 않으며, 구심력만 실제로 작용함',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'Ob', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'G', code:'Ob', name_ko:'장애물은 힘을 가하지 않음', name_en:'Obstacles exert no force',
    description:'정지한 장애물(벽, 바닥 등)은 물체에 힘을 가하지 않는다고 믿음',
    correctConcept:'장애물도 접촉력(수직항력)을 통해 물체에 힘을 가함',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'R1', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'G', code:'R1', name_ko:'질량이 멈추게 함', name_en:'Mass makes things stop',
    description:'질량이 있는 물체는 결국 멈추려는 성질이 있다고 믿음',
    correctConcept:'질량은 관성의 척도이며 멈추려는 성질이 아님. 마찰이 멈추게 함',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'R2', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'G', code:'R2', name_ko:'저항을 극복해야 운동', name_en:'Motion when force overcomes resistance',
    description:'힘이 저항보다 클 때만 운동이 가능하다고 믿음',
    correctConcept:'알짜힘이 0이어도 등속 운동 가능. 힘>저항이면 가속됨',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'R3', unitId:'1', subUnit:'뉴턴 운동 법칙', dimensionCode:'G', code:'R3', name_ko:'저항은 힘/임페투스에 반대', name_en:'Resistance opposes force/impetus',
    description:'저항은 힘이 아닌 임페투스에 반대로 작용한다고 믿음',
    correctConcept:'마찰력은 운동 방향에 반대로 작용하는 실제 힘임',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'G1', unitId:'1', subUnit:'물체의 운동', dimensionCode:'G', code:'G1', name_ko:'공기압이 중력 보조', name_en:'Air pressure-assisted gravity',
    description:'중력은 공기압의 도움을 받아 물체를 아래로 당긴다고 믿음',
    correctConcept:'중력은 공기압과 독립적으로 작용하는 힘임',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'G2', unitId:'1', subUnit:'물체의 운동', dimensionCode:'G', code:'G2', name_ko:'중력은 질량 고유 성질', name_en:'Gravity intrinsic to mass',
    description:'중력은 물체 자체에 내재된 고유한 성질이라고 믿음',
    correctConcept:'중력은 두 물체 사이의 상호작용으로 발생하는 힘임',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'G3', unitId:'1', subUnit:'물체의 운동', dimensionCode:'G', code:'G3', name_ko:'무거운 물체가 더 빨리 낙하', name_en:'Heavier objects fall faster',
    description:'무거운 물체가 가벼운 물체보다 더 빨리 낙하한다고 믿음',
    correctConcept:'공기저항 무시 시 모든 물체는 동일한 중력가속도로 낙하함 (g≈9.8m/s²)',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'G4', unitId:'1', subUnit:'물체의 운동', dimensionCode:'G', code:'G4', name_ko:'낙하 중 중력 증가', name_en:'Gravity increases as objects fall',
    description:'물체가 낙하하면서 중력이 점점 커진다고 믿음',
    correctConcept:'지표면 근처에서 중력가속도 g는 일정함',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  { id:'G5', unitId:'1', subUnit:'물체의 운동', dimensionCode:'G', code:'G5', name_ko:'임페투스 소진 후 중력 작용', name_en:'Gravity acts after impetus wears down',
    description:'던진 물체의 임페투스가 소진된 후에야 중력이 작용하기 시작한다고 믿음',
    correctConcept:'중력은 던지는 순간부터 항상 작용함',
    sourcePaper:'Hestenes, Wells & Swackhamer (1992), The Physics Teacher 30(3)' },
  // 역학적 에너지 보존 (unit 2) — 이종주 (2009)
  { id:'ME1', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME1', name_ko:'경로길이와 속력의 혼동', name_en:'Conflation of path length with velocity',
    description:'같은 높이에서 미끄럼틀을 내려올 때 경로가 길거나 기울기가 다르면 바닥에서의 속력도 달라진다고 믿음',
    correctConcept:'마찰이 없다면 같은 높이에서 출발해 같은 높이에 도달할 때 경로의 길이·기울기와 무관하게 최종 속력은 같다',
    sourcePaper:'이종주 (2009), 연세대학교 교육대학원 석사학위논문, p.93-94' },
  { id:'ME2', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME2', name_ko:'던지는 방향과 속력의 혼동', name_en:'Throwing direction affects final velocity',
    description:'같은 높이·같은 속력으로 공을 위/아래로 던질 때 던지는 방향에 따라 바닥 도달 속력이 달라진다고 믿음',
    correctConcept:'역학적에너지 보존에 의해 같은 높이에 도달할 때 운동에너지(속력)는 던진 방향과 무관하게 같다',
    sourcePaper:'이종주 (2009), 연세대학교 교육대학원 석사학위논문, p.94-95' },
  { id:'ME3', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME3', name_ko:'에너지 보존 조건 오해', name_en:'Misconception about conditions for conservation',
    description:'마찰력 등 비보존력이 작용하는 상황에서도 역학적에너지가 항상 보존된다고 믿음',
    correctConcept:'역학적에너지 보존은 마찰·공기저항 같은 비보존력이 작용하지 않을 때만 성립한다',
    sourcePaper:'이종주 (2009), 연세대학교 교육대학원 석사학위논문, p.93' },
  { id:'ME4', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME4', name_ko:'에너지와 운동량의 혼동', name_en:'Confusion between energy and momentum',
    description:'역학적에너지 보존과 운동량 보존을 구분하지 못하고 항상 함께 보존된다고 믿음',
    correctConcept:'탄성충돌은 운동량과 운동에너지가 모두 보존되지만, 비탄성충돌은 운동량만 보존되고 운동에너지는 일부 손실된다',
    sourcePaper:'이종주 (2009), 연세대학교 교육대학원 석사학위논문, p.39' },
  { id:'ME5', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME5', name_ko:'질량과 속력의 혼동', name_en:'Mass affects final velocity on frictionless surfaces',
    description:'질량이 다른 두 물체가 마찰 없는 경사면을 같은 높이에서 내려올 때 무거운 물체가 더 빠르다고 믿음',
    correctConcept:'마찰이 없다면 질량과 무관하게 같은 높이에서 도달한 최종 속력은 v=√(2gh)로 동일하다',
    sourcePaper:'이종주 (2009), 연세대학교 교육대학원 석사학위논문, p.96' },
  { id:'ME6', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME6', name_ko:'충돌 시 운동에너지 보존 오해', name_en:'Misconception about kinetic energy in collisions',
    description:'탄성충돌과 비탄성충돌을 구분하지 못하고 모든 충돌에서 운동에너지가 보존된다고 믿음',
    correctConcept:'비탄성충돌에서는 운동량만 보존되고 운동에너지의 일부는 열·소리·변형 에너지로 손실된다',
    sourcePaper:'이종주 (2009), 연세대학교 교육대학원 석사학위논문, p.94' },
  { id:'ME7', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME7', name_ko:'위치에너지 기준점 혼동', name_en:'Misconception about reference point for potential energy',
    description:'위치에너지를 계산할 때 기준면으로부터의 높이를 명확히 하지 못하고 절대 높이와 혼동함',
    correctConcept:'위치에너지는 선택한 기준면으로부터의 높이에 비례하는 상대적인 값이다',
    sourcePaper:'이종주 (2009), 연세대학교 교육대학원 석사학위논문, p.41-42' },
  // 역학적 에너지 보존 (unit 2) — 정현 (2021)
  { id:'ME8', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME8', name_ko:'운동에너지 크기비교 오류', name_en:'Misconception about kinetic energy magnitude comparison',
    description:'운동에너지가 속력의 제곱에 비례한다는 공식은 알지만, 실제 비교 시 속력에만 비례한다고 잘못 적용함',
    correctConcept:'운동에너지 KE=(1/2)mv²이므로 속력이 2배가 되면 운동에너지는 4배가 된다',
    sourcePaper:'정현 (2021), 충북대학교 대학원 석사학위논문, p.42-52' },
  { id:'ME9', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME9', name_ko:'위치에너지 기준점 오개념', name_en:'Misconception about height from reference point',
    description:'위치에너지를 비교할 때 기준면으로부터의 높이를 올바르게 설정하지 못하고 높이 차이를 혼동함',
    correctConcept:'위치에너지 PE=mgh이므로 명확히 정한 기준면으로부터의 높이만 고려해야 한다',
    sourcePaper:'정현 (2021), 충북대학교 대학원 석사학위논문, p.45-47' },
  { id:'ME10', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME10', name_ko:'에너지 보존 개념 미획득', name_en:'Failure to acquire mechanical energy conservation concept',
    description:'위치에너지와 운동에너지를 서로 관련짓지 못하거나 힘과 에너지 개념을 구분하지 못함',
    correctConcept:'역학적에너지(=위치에너지+운동에너지)는 비보존력이 없을 때 일정하게 유지되며, 위치에너지 감소분만큼 운동에너지가 증가한다',
    sourcePaper:'정현 (2021), 충북대학교 대학원 석사학위논문, p.59-68' },
  { id:'ME11', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME11', name_ko:'위치-운동에너지 역비례 오해', name_en:'Misconception about inverse relationship between PE and KE',
    description:'한 지점 내에서의 위치·운동에너지 역비례 관계와, 초기 높이에 따라 전체 역학적에너지가 달라지는 보존 개념을 혼동함',
    correctConcept:'한 지점에서 위치에너지가 클수록 운동에너지는 작지만, 초기 높이가 높을수록 최저점에서의 운동에너지(속력)는 더 커진다',
    sourcePaper:'정현 (2021), 충북대학교 대학원 석사학위논문, p.61-63' },
  { id:'ME12', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME12', name_ko:'에너지와 속력의 혼동', name_en:'Confusing energy with velocity',
    description:'운동에너지와 속력을 구분하지 못하고 "빠르다"와 "에너지가 크다"를 같은 의미로 사용함',
    correctConcept:'운동에너지는 속력의 제곱에 비례하는 별개의 물리량이며 속력 자체와 동일하지 않다',
    sourcePaper:'정현 (2021), 충북대학교 대학원 석사학위논문, p.59-69' },
  { id:'ME13', unitId:'2', subUnit:'역학적 에너지 보존', dimensionCode:'ME', code:'ME13', name_ko:'초기 상태 고려 실패', name_en:'Ignoring initial state in conservation problems',
    description:'진자 등 계의 현재 위치만 고려하고 초기 위치에너지의 크기가 전체 역학적에너지를 결정한다는 점을 고려하지 못함',
    correctConcept:'초기 높이가 높을수록 전체 역학적에너지가 크며, 진자가 도달 가능한 최고점도 초기 높이로 제한된다',
    sourcePaper:'정현 (2021), 충북대학교 대학원 석사학위논문, p.50-68' },
  // 파동의 간섭 (unit 4) — Yun et al. (2025)
  { id:'WI1', unitId:'4', subUnit:'파동의 간섭', dimensionCode:'WI', code:'WI1', name_ko:'진폭 물리량 혼동', name_en:'Confusion about what "amplitude" represents',
    description:'음파 간섭에서 합성파의 "진폭"을 음압 진폭이 아닌 매질 변위 진폭으로 해석함 (조사 대상 67%)',
    correctConcept:'소리의 간섭은 스칼라량인 음압의 합성으로 설명되며, 같은 위상의 음파가 만나면 음압 진폭이 커져 보강간섭이 일어난다',
    sourcePaper:'Yun, Kwak & Choi (2025), 새물리 75(10), p.744, 752-753' },
  { id:'WI2', unitId:'4', subUnit:'파동의 간섭', dimensionCode:'WI', code:'WI2', name_ko:'마주보는 음원 중앙 간섭 오개념', name_en:'Misconception about interference at midpoint of opposing speakers',
    description:'매질 변위를 벡터로 상쇄시키는 논리로, 마주보는 두 스피커 정중앙에서 상쇄간섭이 일어난다고 잘못 판단함',
    correctConcept:'중앙에서는 두 음파가 위상차 없이 만나 음압 진폭이 최대가 되므로 보강간섭이 일어난다 (음압과 변위는 위상이 90˚ 어긋남)',
    sourcePaper:'Yun, Kwak & Choi (2025), 새물리 75(10), p.750, 752-753' },
  { id:'WI3', unitId:'4', subUnit:'파동의 간섭', dimensionCode:'WI', code:'WI3', name_ko:'종파 변위 벡터합 오용', name_en:'Incorrect application of displacement vector addition to longitudinal waves',
    description:'종파인 음파의 간섭을 매질 변위 벡터의 합으로만 분석하려 하여 2차원 공간에서의 보강·상쇄를 올바로 구분하지 못함',
    correctConcept:'음파 간섭은 스칼라량인 음압의 합으로 분석해야 하며, 변위 벡터합만으로는 압력 변화를 설명할 수 없다',
    sourcePaper:'Yun, Kwak & Choi (2025), 새물리 75(10), p.746-748' },
  { id:'WI4', unitId:'4', subUnit:'파동의 간섭', dimensionCode:'WI', code:'WI4', name_ko:'교과서 진폭 표기 모호성', name_en:"Textbook's ambiguous use of amplitude in interference description",
    description:'"위상이 같으면 진폭이 커진다"는 교과서 서술이 음압 진폭인지 변위 진폭인지 명시하지 않아 변위로 오해하게 됨',
    correctConcept:'간섭을 설명할 때는 다루는 진폭이 음압의 진폭임을 명확히 표기해야 한다',
    sourcePaper:'Yun, Kwak & Choi (2025), 새물리 75(10), p.750-751' },
  { id:'WI5', unitId:'4', subUnit:'파동의 간섭', dimensionCode:'WI', code:'WI5', name_ko:'횡파 표현으로 인한 종파 특성 간과', name_en:'Sinusoidal representation obscuring longitudinal nature of sound',
    description:'교과서가 소리(종파)를 이해하기 쉽도록 사인곡선(횡파 형태)으로 표현하는 관행 때문에 종파 특성과 음압의 스칼라적 성질을 간과함',
    correctConcept:'음파는 종파이며 음압은 스칼라량으로 단순 덧셈으로 합성된다는 점을 매질 입자의 진동 방향(벡터)과 구분해 이해해야 한다',
    sourcePaper:'Yun, Kwak & Choi (2025), 새물리 75(10), p.747-748' },
  // 물질의 이중성 (unit 4) — 이창열 (2021)
  { id:'MD1', unitId:'4', subUnit:'물질의 이중성', dimensionCode:'MD', code:'MD1', name_ko:'불확정성 원리 원인 오해', name_en:'Misconception that uncertainty arises from measurement device limits',
    description:'전자 등 입자의 위치·운동량을 동시에 정확히 측정할 수 없는 불확정성의 원인을 측정 장비의 정밀도 한계로 오해함',
    correctConcept:'불확정성 원리는 측정 장비의 정밀성과 무관하게 근본적으로 존재하는 물리적 한계이며 Δx·Δp≥ℏ/2로 표현된다',
    sourcePaper:'이창열 (2021), 서울대학교 사범대학 물리교육과 학사학위논문, p.5' },

  // ── 운동량 (unit 2) — 이종주 (2009) ──────────────────────────────────────
  { id:'MO1', unitId:'2', subUnit:'운동량과 충격량', dimensionCode:'MO', code:'MO1', name_ko:'충돌 후 질량 큰 쪽이 더 빠르다', name_en:'Heavier object moves faster after collision',
    description:'충돌 후 질량이 큰 물체가 더 빠르게 움직인다고 믿음',
    correctConcept:'충돌 후 속도는 운동량 보존 법칙으로 결정되며 질량이 클수록 속도는 오히려 더 작아질 수 있다',
    sourcePaper:'이종주 (2009), 연세대학교 교육대학원 석사학위논문' },
  { id:'MO2', unitId:'2', subUnit:'운동량과 충격량', dimensionCode:'MO', code:'MO2', name_ko:'완전비탄성충돌 시 운동량 감소', name_en:'Momentum decreases in perfectly inelastic collision',
    description:'두 물체가 충돌 후 합쳐지면 운동량이 손실된다고 믿음',
    correctConcept:'충돌 형태(탄성/비탄성)와 무관하게 외력이 없으면 총 운동량은 보존된다',
    sourcePaper:'이종주 (2009), 연세대학교 교육대학원 석사학위논문' },
  { id:'MO3', unitId:'2', subUnit:'운동량과 충격량', dimensionCode:'MO', code:'MO3', name_ko:'운동량 클수록 가속도 증가', name_en:'Greater momentum implies greater acceleration',
    description:'운동량이 클수록 가속도도 크다고 믿음',
    correctConcept:'가속도는 알짜힘을 질량으로 나눈 값(a=F/m)이며 운동량의 크기와 직접적 관계가 없다',
    sourcePaper:'이종주 (2009), 연세대학교 교육대학원 석사학위논문' },

  // ── 전기 회로 (unit 3) — 이승노 (2006) ──────────────────────────────────
  { id:'EC1', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'EC', code:'EC1', name_ko:'직렬회로 전류 소모 모형', name_en:'Current consumption model in series circuit',
    description:'전류가 각 소자에서 소비되어 회로 뒤쪽으로 갈수록 전류가 줄어든다고 믿음',
    correctConcept:'직렬 회로에서 전류는 모든 소자에서 동일하며, 소자는 전류가 아닌 전기에너지를 소비한다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },
  { id:'EC2', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'EC', code:'EC2', name_ko:'전압·전류 혼동', name_en:'Confusion between voltage and current',
    description:'전압과 전류를 같은 개념으로 혼동하여 서로 교환 가능한 것으로 생각함',
    correctConcept:'전압(V)은 전기적 위치에너지 차이이고, 전류(A)는 단위 시간당 이동하는 전하량으로 서로 다른 물리량이다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },
  { id:'EC3', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'EC', code:'EC3', name_ko:'병렬 연결 = 저항 증가', name_en:'Parallel connection increases total resistance',
    description:'저항을 병렬로 연결하면 전체 저항이 증가한다고 믿음',
    correctConcept:'저항을 병렬로 연결하면 전류 경로가 늘어나 전체 저항은 각 저항보다 작아진다 (1/R합 = 1/R1 + 1/R2)',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },
  { id:'EC4', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'EC', code:'EC4', name_ko:'전지 거리 비례 전류', name_en:'Current weakens with distance from battery',
    description:'전지에서 멀수록 전류가 약해진다고 믿음',
    correctConcept:'이상적인 도선에서 전류는 위치에 관계없이 일정하며, 전지의 기전력이 회로 전체를 순환하는 전류를 결정한다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },
  { id:'EC5', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'EC', code:'EC5', name_ko:'전류 방향 = 전자 이동 방향', name_en:'Current flows in the same direction as electrons',
    description:'전류의 방향이 전자의 이동 방향과 같다고 믿음',
    correctConcept:'전류의 방향은 양(+)전하의 이동 방향으로 정의되며, 전자(음전하)의 이동 방향과 반대이다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },
  { id:'EC6', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'EC', code:'EC6', name_ko:'저항 = 전류 차단', name_en:'Resistance completely blocks current',
    description:'저항은 전류를 완전히 막는 장치라고 믿음',
    correctConcept:'저항은 전류의 흐름을 방해하지만 차단하지는 않는다. 전류는 I=V/R 로 저항에 반비례하여 흐른다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },

  // ── 자기장 (unit 3) — 이승노 (2006) ─────────────────────────────────────
  { id:'MF1', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'MF', code:'MF1', name_ko:'직선 도선 자기장 방향 오해', name_en:'Magnetic field direction parallel to current',
    description:'직선 도선 주변의 자기장이 전류 방향과 평행하게 형성된다고 믿음',
    correctConcept:'직선 도선 주변의 자기장은 전류 방향에 수직한 동심원 형태로 형성된다 (오른나사 법칙)',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },
  { id:'MF2', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'MF', code:'MF2', name_ko:'자기장 세기 거리 무관', name_en:'Magnetic field strength independent of distance',
    description:'도선에서 멀어져도 자기장의 세기가 일정하다고 믿음',
    correctConcept:'직선 도선에서 자기장의 세기는 거리에 반비례한다 (B ∝ 1/r)',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },
  { id:'MF3', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'MF', code:'MF3', name_ko:'같은 방향 전류 도선 = 반발', name_en:'Parallel currents in same direction repel',
    description:'같은 방향으로 전류가 흐르는 두 평행 도선이 서로 밀어낸다고 믿음',
    correctConcept:'같은 방향으로 전류가 흐르는 두 평행 도선은 서로 당기는 힘(인력)이 작용한다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },
  { id:'MF4', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'MF', code:'MF4', name_ko:'N극에서만 자기력선 시작', name_en:'Magnetic field lines only emerge from N pole',
    description:'자기력선이 N극에서만 나오고 S극으로 들어가지 않는다고 믿음',
    correctConcept:'자기력선은 N극에서 나와 S극으로 들어가는 연속된 닫힌 곡선이며, 도중에 끊어지거나 생성/소멸하지 않는다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },
  { id:'MF5', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'MF', code:'MF5', name_ko:'코일 자기장 방향 직관 판단', name_en:'Intuitive judgment of coil magnetic field direction',
    description:'오른손 법칙을 적용하지 않고 직관적으로 코일 내부 자기장 방향을 판단함',
    correctConcept:'코일 내부 자기장 방향은 오른손 법칙(전류 방향으로 손가락을 감을 때 엄지 방향)으로 결정해야 한다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },
  { id:'MF6', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'MF', code:'MF6', name_ko:'자기장 세기 전류 비례 부정', name_en:'Magnetic field not proportional to current',
    description:'전류를 2배로 늘려도 자기장이 2배가 되지 않는다고 믿음',
    correctConcept:'직선 도선에서 자기장의 세기는 전류에 비례한다 (B ∝ I). 전류가 2배이면 자기장도 2배이다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },
  { id:'MF7', unitId:'3', subUnit:'전류의 자기 작용', dimensionCode:'MF', code:'MF7', name_ko:'전자석·영구자석 원리 무관', name_en:'Electromagnet and permanent magnet operate on different principles',
    description:'전자석과 영구자석의 자기장은 전혀 다른 원리로 발생한다고 믿음',
    correctConcept:'영구자석의 자기장도 원자 내 전자의 스핀과 궤도 운동(전류)에서 비롯되므로 전자석과 같은 원리다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문' },

  // ── 전자기 유도 (unit 3) — 이승노 (2006) + 연구 기반 추론 ─────────────────
  { id:'EMI1', unitId:'3', subUnit:'전자기 유도', dimensionCode:'EMI', code:'EMI1', name_ko:'정지 자석 = 유도 전류', name_en:'Stationary magnet induces current',
    description:'자석이 코일 근처에 정지해 있기만 해도 유도 전류가 흐른다고 믿음',
    correctConcept:'전자기 유도는 자기선속의 변화가 있을 때만 발생한다. 자석이 정지해 있으면 자기선속 변화가 없으므로 유도 전류가 흐르지 않는다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문; 연구 기반 추론' },
  { id:'EMI2', unitId:'3', subUnit:'전자기 유도', dimensionCode:'EMI', code:'EMI2', name_ko:'자기장 세기 = 유도 기전력', name_en:'Stronger magnetic field always means larger EMF',
    description:'자기장이 강하면 무조건 유도 기전력이 크다고 믿음',
    correctConcept:'유도 기전력의 크기는 자기선속의 변화율(ΔΦ/Δt)에 비례한다. 자기장이 강해도 변화가 없으면 유도 기전력은 0이다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문; 연구 기반 추론' },
  { id:'EMI3', unitId:'3', subUnit:'전자기 유도', dimensionCode:'EMI', code:'EMI3', name_ko:'개방 회로에서 유도 전류', name_en:'Induced current flows in open circuit',
    description:'폐회로가 아니어도 유도 전류가 흐른다고 믿음',
    correctConcept:'유도 전류가 흐르려면 폐회로가 형성되어야 한다. 개방 회로에서는 유도 기전력이 발생해도 전류는 흐르지 않는다',
    sourcePaper:'연구 기반 추론' },
  { id:'EMI4', unitId:'3', subUnit:'전자기 유도', dimensionCode:'EMI', code:'EMI4', name_ko:'유도 전류 방향 = N극 방향', name_en:'Induced current direction follows N pole direction',
    description:'유도 전류의 방향이 자석 N극이 향하는 방향과 같다고 믿음',
    correctConcept:'유도 전류의 방향은 렌츠의 법칙으로 결정된다. 자속 변화를 방해하는 방향으로 유도 전류가 흐르며 N극 방향과 직접적 관계는 없다',
    sourcePaper:'이승노 (2006), 전·자기 영역의 오개념 분석, 한국교원대학교 석사학위논문; 연구 기반 추론' },
  { id:'EMI5', unitId:'3', subUnit:'전자기 유도', dimensionCode:'EMI', code:'EMI5', name_ko:'렌츠 법칙 = 완전 상쇄', name_en:'Lenz\'s law means complete cancellation of magnetic field',
    description:'유도 전류가 원래 자기장을 항상 완전히 상쇄시킨다고 믿음',
    correctConcept:'렌츠의 법칙은 유도 전류가 자속 변화를 방해하는 방향으로 흐름을 의미하며, 자기장을 완전히 상쇄시키지는 않는다',
    sourcePaper:'연구 기반 추론' },

  // ── 원자 모형 (unit 3) — 장숙경 (2014) ──────────────────────────────────
  { id:'AT1', unitId:'3', subUnit:'원자 모형과 전기력', dimensionCode:'AT', code:'AT1', name_ko:'스펙트럼 선 = 원자 속 입자', name_en:'Spectral lines represent particles inside atom',
    description:'선 스펙트럼의 각 선이 원자 속 입자를 나타낸다고 믿음 (고1 135명 조사에서 다수 확인)',
    correctConcept:'선 스펙트럼의 각 선은 전자가 에너지 준위 사이를 전이할 때 방출하는 빛의 파장을 나타내며 입자와 무관하다',
    sourcePaper:'장숙경 (2014), 원자 모형과 그 변천 과정에 대한 고등학생들의 이해 조사, 이화여대 석사학위논문' },
  { id:'AT2', unitId:'3', subUnit:'원자 모형과 전기력', dimensionCode:'AT', code:'AT2', name_ko:'스펙트럼선↔에너지 준위 미연결', name_en:'Spectral lines not connected to energy level transitions',
    description:'스펙트럼 선이 전자의 에너지 준위 차이와 관련됨을 이해하지 못함',
    correctConcept:'전자가 높은 에너지 준위에서 낮은 준위로 전이할 때 두 준위의 에너지 차이에 해당하는 파장의 빛을 방출하며, 이것이 선 스펙트럼으로 나타난다',
    sourcePaper:'장숙경 (2014), 원자 모형과 그 변천 과정에 대한 고등학생들의 이해 조사, 이화여대 석사학위논문' },
  { id:'AT3', unitId:'3', subUnit:'원자 모형과 전기력', dimensionCode:'AT', code:'AT3', name_ko:'에너지 불연속 개념 미획득', name_en:'Failure to understand discrete energy levels',
    description:'원자 내 전자 에너지가 불연속적(양자화)이라는 개념을 이해하지 못하고 연속적으로 변한다고 생각함',
    correctConcept:'원자 내 전자는 특정 에너지 값(에너지 준위)만 가질 수 있으며, 그 사이 값의 에너지는 가질 수 없다',
    sourcePaper:'장숙경 (2014), 원자 모형과 그 변천 과정에 대한 고등학생들의 이해 조사, 이화여대 석사학위논문' },
  { id:'AT4', unitId:'3', subUnit:'원자 모형과 전기력', dimensionCode:'AT', code:'AT4', name_ko:'오비탈 = 전자 궤도', name_en:'Orbital is the actual orbit of electron',
    description:'오비탈이 확률밀도 분포가 아닌 전자가 실제로 도는 궤도라고 믿음',
    correctConcept:'오비탈은 전자가 발견될 확률이 높은 공간 영역(확률밀도함수)이며, 전자가 일정한 궤도를 도는 것이 아니다',
    sourcePaper:'장숙경 (2014), 원자 모형과 그 변천 과정에 대한 고등학생들의 이해 조사, 이화여대 석사학위논문' },
  { id:'AT5', unitId:'3', subUnit:'원자 모형과 전기력', dimensionCode:'AT', code:'AT5', name_ko:'점밀도 그림 점 = 개별 전자', name_en:'Dots in electron cloud represent individual electrons',
    description:'오비탈을 점밀도로 표현한 그림에서 각 점을 실제 전자의 위치로 인식함',
    correctConcept:'점밀도 그림의 점은 전자가 그 위치에서 발견될 확률의 상대적 크기를 나타내며, 전자 개수를 의미하지 않는다',
    sourcePaper:'장숙경 (2014), 원자 모형과 그 변천 과정에 대한 고등학생들의 이해 조사, 이화여대 석사학위논문' },
  { id:'AT6', unitId:'3', subUnit:'원자 모형과 전기력', dimensionCode:'AT', code:'AT6', name_ko:'에너지 준위 = 원자핵 거리', name_en:'Energy level determined only by distance from nucleus',
    description:'전자의 에너지 준위를 원자핵과의 거리로만 판단하는 보어 모형에 고착됨 (64명 조사에서 31.3%만 정답)',
    correctConcept:'현대 원자 모형에서 전자의 에너지는 주양자수(n)와 각운동량 양자수(l) 등 여러 양자수로 결정되며 단순한 거리와 1:1 대응이 아니다',
    sourcePaper:'장숙경 (2013/2014), 과학 글쓰기를 통한 원자 모형과 오비탈에 대한 고등학생들의 개념 분석, 이화여대' },

  // ── 에너지 띠와 반도체 (unit 3) — 장숙경(2014) 간접 근거 기반 추론 ──────
  { id:'EB1', unitId:'3', subUnit:'에너지 띠와 반도체', dimensionCode:'EB', code:'EB1', name_ko:'에너지 띠 ≠ 에너지 준위 연장', name_en:'Energy band not seen as extension of atomic energy levels',
    description:'에너지 띠가 원자의 에너지 준위들이 모여 형성된다는 연결을 이해하지 못함',
    correctConcept:'고체에서 수많은 원자의 에너지 준위들이 매우 촘촘하게 모여 거의 연속적인 에너지 띠를 형성한다',
    sourcePaper:'장숙경 (2014), 원자 모형 오개념 연구 간접 근거; 연구 기반 추론' },
  { id:'EB2', unitId:'3', subUnit:'에너지 띠와 반도체', dimensionCode:'EB', code:'EB2', name_ko:'반도체 = 불완전 도체', name_en:'Semiconductor seen as imperfect conductor',
    description:'반도체를 에너지 띠 간격으로 설명되는 별개 물질이 아닌 "나쁜 도체"로만 인식함',
    correctConcept:'도체·반도체·절연체의 차이는 전도띠와 원자가띠 사이의 에너지 간격(띠 간격) 크기로 설명된다',
    sourcePaper:'장숙경 (2014), 원자 모형 오개념 연구 간접 근거; 연구 기반 추론' },
  { id:'EB3', unitId:'3', subUnit:'에너지 띠와 반도체', dimensionCode:'EB', code:'EB3', name_ko:'도핑 → 전하 생성', name_en:'Doping creates new charges',
    description:'도핑이 새로운 전하를 만들어낸다고 믿음 (전하 이동이 아닌 생성으로 오해)',
    correctConcept:'도핑은 원자가 전자 수가 다른 불순물을 추가해 자유 전자 또는 양공(정공)을 늘리는 것이며, 전체 전하는 보존된다',
    sourcePaper:'연구 기반 추론' },

  // ── 파동·굴절 (unit 4) — 최정훈 (2015) ──────────────────────────────────
  { id:'WR1', unitId:'4', subUnit:'파동의 진동과 굴절', dimensionCode:'WR', code:'WR1', name_ko:'굴절 시 속도 불변', name_en:'Speed unchanged during refraction',
    description:'빛이 굴절할 때 속도는 변하지 않고 방향만 바뀐다고 믿음',
    correctConcept:'빛이 굴절하는 근본 원인은 매질에 따라 빛의 속도가 달라지기 때문이다 (v=c/n)',
    sourcePaper:'최정훈 (2015), 중학교 학생들의 빛 관련 오개념 연구, 충북대학교 석사학위논문' },
  { id:'WR2', unitId:'4', subUnit:'파동의 진동과 굴절', dimensionCode:'WR', code:'WR2', name_ko:'굴절각 클수록 속도 증가', name_en:'Larger refraction angle means faster speed',
    description:'굴절각이 클수록 빛의 속도가 빠르다고 믿음',
    correctConcept:'굴절각이 클수록 해당 매질에서의 빛의 속도가 빠른 것은 맞으나, 굴절각 자체가 속도를 결정하는 것이 아니라 매질의 굴절률이 속도를 결정한다',
    sourcePaper:'최정훈 (2015), 중학교 학생들의 빛 관련 오개념 연구, 충북대학교 석사학위논문' },
  { id:'WR3', unitId:'4', subUnit:'파동의 진동과 굴절', dimensionCode:'WR', code:'WR3', name_ko:'전반사 = 모든 각도 가능', name_en:'Total internal reflection can occur at any angle',
    description:'전반사가 어떤 각도에서도 일어날 수 있다고 믿음',
    correctConcept:'전반사는 빛이 굴절률이 큰 매질에서 작은 매질로 진행할 때 입사각이 임계각보다 클 경우에만 일어난다',
    sourcePaper:'최정훈 (2015), 중학교 학생들의 빛 관련 오개념 연구, 충북대학교 석사학위논문' },
  { id:'WR4', unitId:'4', subUnit:'파동의 진동과 굴절', dimensionCode:'WR', code:'WR4', name_ko:'굴절 시 파장 불변', name_en:'Wavelength unchanged during refraction',
    description:'빛이 굴절할 때 파장이 변하지 않는다고 믿음 (진동수와 파장을 혼동)',
    correctConcept:'빛이 다른 매질로 진행할 때 진동수는 변하지 않지만 속도가 변하므로 파장(λ=v/f)도 변한다',
    sourcePaper:'최정훈 (2015), 중학교 학생들의 빛 관련 오개념 연구, 충북대학교 석사학위논문' },

  // ── 빛의 이중성 (unit 4) — 예비교사 연구 (서울대 박사, 2006) + 최정훈 (2015)
  { id:'LD1', unitId:'4', subUnit:'빛의 이중성', dimensionCode:'LD', code:'LD1', name_ko:'빛 세기 ↑ = 광전자 운동에너지 ↑', name_en:'Brighter light ejects faster photoelectrons',
    description:'빛의 세기가 강할수록 튀어나오는 광전자의 운동에너지가 커진다고 믿음',
    correctConcept:'광전자의 최대 운동에너지는 빛의 진동수(색)에만 의존한다. 빛의 세기는 광전자의 수에만 영향을 준다 (Ek = hf - W)',
    sourcePaper:'물리 예비교사들의 빛의 간섭과 회절에 대한 오개념 분석 (서울대 박사학위논문, 2006)' },
  { id:'LD2', unitId:'4', subUnit:'빛의 이중성', dimensionCode:'LD', code:'LD2', name_ko:'입자성·파동성 동시 발현', name_en:'Wave and particle nature appear simultaneously',
    description:'빛이 입자성과 파동성을 항상 동시에 드러낸다고 믿음',
    correctConcept:'빛은 관찰 방식에 따라 파동성(간섭·회절 실험)이나 입자성(광전효과)으로 나타나며, 두 성질이 동시에 관측되지는 않는다',
    sourcePaper:'물리 예비교사들의 빛의 간섭과 회절에 대한 오개념 분석 (서울대 박사학위논문, 2006)' },
  { id:'LD3', unitId:'4', subUnit:'빛의 이중성', dimensionCode:'LD', code:'LD3', name_ko:'물질파 파장 = 입자 크기 비례', name_en:'de Broglie wavelength proportional to particle size',
    description:'드브로이 파장이 클수록 입자가 크다고 믿음',
    correctConcept:'드브로이 파장은 λ=h/mv 로 입자의 운동량에 반비례한다. 입자의 크기와는 관계없다',
    sourcePaper:'물리 예비교사들의 빛의 간섭과 회절에 대한 오개념 분석 (서울대 박사학위논문, 2006)' },
  { id:'LD4', unitId:'4', subUnit:'빛의 이중성', dimensionCode:'LD', code:'LD4', name_ko:'간섭·회절 = 입자성', name_en:'Interference and diffraction explained by particle nature',
    description:'빛의 간섭·회절 현상이 파동성이 아닌 입자성으로 설명된다고 믿음',
    correctConcept:'간섭과 회절은 파동의 특성으로 빛의 파동성을 보여주는 현상이다. 입자로는 간섭·회절을 설명할 수 없다',
    sourcePaper:'물리 예비교사들의 빛의 간섭과 회절에 대한 오개념 분석 (서울대 박사학위논문, 2006)' },
];

/* ============================================================
   4. MISCONCEPTION SENTENCES
   ============================================================ */
const sentences = [
  { misconceptionId:'I3', isWrong:true,  sentence:'물체가 등속도로 운동하려면 계속 힘을 주어야 한다', difficulty:2 },
  { misconceptionId:'I3', isWrong:true,  sentence:'힘이 사라지면 물체는 곧 속도가 줄어 멈추게 된다', difficulty:2 },
  { misconceptionId:'I3', isWrong:false, sentence:'외력의 합이 0이면 물체는 등속도 직선 운동을 유지한다', difficulty:2 },
  { misconceptionId:'I3', isWrong:false, sentence:'마찰이 없는 경우 처음에만 힘을 주면 이후 등속 운동이 유지된다', difficulty:2 },
  { misconceptionId:'I3', isWrong:false, sentence:'등속 운동에서도 중력과 수직항력 같은 힘은 작용할 수 있다', difficulty:3 },
  { misconceptionId:'AR1', isWrong:true,  sentence:'충돌할 때 무거운 물체가 가벼운 물체에 더 큰 힘을 가한다', difficulty:2 },
  { misconceptionId:'AR1', isWrong:true,  sentence:'트럭이 자전거보다 더 큰 힘으로 충돌 상대를 민다', difficulty:2 },
  { misconceptionId:'AR1', isWrong:false, sentence:'뉴턴 제3법칙에 따라 두 물체가 서로 가하는 힘의 크기는 항상 같다', difficulty:2 },
  { misconceptionId:'AR1', isWrong:false, sentence:'작용과 반작용은 질량에 관계없이 크기가 같고 방향이 반대이다', difficulty:2 },
  { misconceptionId:'AR2', isWrong:true,  sentence:'움직이는 자동차가 정지한 트럭보다 더 큰 힘을 가한다', difficulty:2 },
  { misconceptionId:'AR2', isWrong:false, sentence:'작용-반작용은 어느 물체가 능동적인지와 관계없이 크기가 같다', difficulty:2 },
  { misconceptionId:'K1', isWrong:true,  sentence:'물체가 높은 위치에 있으면 속도도 크다', difficulty:2 },
  { misconceptionId:'K1', isWrong:false, sentence:'위치와 속도는 독립적인 물리량으로 위치가 높다고 속도가 크지 않다', difficulty:2 },
  { misconceptionId:'K2', isWrong:true,  sentence:'속도가 클수록 가속도도 크다', difficulty:2 },
  { misconceptionId:'K2', isWrong:true,  sentence:'물체가 빠르게 움직이면 가속도도 크다', difficulty:1 },
  { misconceptionId:'K2', isWrong:false, sentence:'가속도는 속도의 변화율이므로 속도가 일정하면 가속도는 0이다', difficulty:2 },
  { misconceptionId:'K2', isWrong:false, sentence:'등속 운동 중인 물체의 가속도는 빠르게 달려도 0이다', difficulty:2 },
  { misconceptionId:'K3', isWrong:true,  sentence:'동쪽 3m/s, 북쪽 4m/s로 동시에 움직이면 합속도는 7m/s이다', difficulty:2 },
  { misconceptionId:'K3', isWrong:false, sentence:'속도는 벡터이므로 동쪽 3m/s와 북쪽 4m/s의 합속도는 5m/s(북동 방향)이다', difficulty:2 },
  { misconceptionId:'AF1', isWrong:true,  sentence:'정지한 벽은 기대고 있는 사람에게 힘을 가하지 않는다', difficulty:1 },
  { misconceptionId:'AF1', isWrong:false, sentence:'정지한 벽도 기대는 사람에게 수직항력을 통해 힘을 가한다', difficulty:2 },
  { misconceptionId:'AF2', isWrong:true,  sentence:'물체가 움직이고 있다면 반드시 알짜힘이 작용하고 있다', difficulty:2 },
  { misconceptionId:'AF2', isWrong:false, sentence:'등속 운동하는 물체의 알짜힘은 0이다', difficulty:1 },
  { misconceptionId:'AF3', isWrong:true,  sentence:'정지해 있는 물체에는 아무런 힘도 작용하지 않는다', difficulty:1 },
  { misconceptionId:'AF3', isWrong:true,  sentence:'물체가 움직이지 않으면 알짜힘이 없다는 뜻이다', difficulty:2 },
  { misconceptionId:'AF3', isWrong:false, sentence:'정지한 물체에도 중력과 수직항력이 작용하며 알짜힘이 0인 것이다', difficulty:2 },
  { misconceptionId:'AF3', isWrong:false, sentence:'힘이 작용해도 알짜힘이 0이면 물체는 정지 상태를 유지한다', difficulty:3 },
  { misconceptionId:'AF4', isWrong:true,  sentence:'힘을 두 배로 늘리면 속도도 두 배가 된다', difficulty:2 },
  { misconceptionId:'AF4', isWrong:false, sentence:'힘을 두 배로 늘리면 가속도가 두 배가 되며, 속도는 시간에 따라 변한다', difficulty:2 },
  { misconceptionId:'AF5', isWrong:true,  sentence:'물체가 점점 빨라지고 있다면 작용하는 힘도 점점 커지고 있다', difficulty:2 },
  { misconceptionId:'AF5', isWrong:false, sentence:'일정한 힘이 작용하면 가속도가 일정하며 속도는 균일하게 증가한다', difficulty:2 },
  { misconceptionId:'CI1', isWrong:true,  sentence:'두 힘이 작용할 때 더 큰 힘의 방향으로만 운동한다', difficulty:2 },
  { misconceptionId:'CI1', isWrong:false, sentence:'운동 방향은 모든 힘의 벡터 합인 알짜힘의 방향으로 결정된다', difficulty:2 },
  { misconceptionId:'CF',  isWrong:true,  sentence:'원운동하는 물체에는 바깥쪽으로 원심력이 실제로 작용한다', difficulty:2 },
  { misconceptionId:'CF',  isWrong:false, sentence:'관성계에서 원심력은 존재하지 않으며 안쪽 방향의 구심력만 실제 힘이다', difficulty:3 },
  { misconceptionId:'G3',  isWrong:true,  sentence:'무거운 물체가 가벼운 물체보다 더 빨리 떨어진다', difficulty:1 },
  { misconceptionId:'G3',  isWrong:true,  sentence:'쇠공이 깃털보다 빨리 낙하하는 이유는 중력이 더 크게 작용하기 때문이다', difficulty:2 },
  { misconceptionId:'G3',  isWrong:false, sentence:'공기저항이 없다면 모든 물체는 질량에 관계없이 같은 가속도로 낙하한다', difficulty:2 },
  { misconceptionId:'G3',  isWrong:false, sentence:'중력가속도 g는 물체의 질량에 무관하게 약 9.8m/s²로 일정하다', difficulty:2 },
  { misconceptionId:'G4',  isWrong:true,  sentence:'낙하할수록 중력이 점점 강해져 가속도가 커진다', difficulty:2 },
  { misconceptionId:'G4',  isWrong:false, sentence:'지표면 근처에서 중력가속도는 낙하 거리와 무관하게 일정하다', difficulty:2 },
  { misconceptionId:'G5',  isWrong:true,  sentence:'위로 던진 공은 최고점에 도달해야 비로소 중력의 영향을 받기 시작한다', difficulty:2 },
  { misconceptionId:'G5',  isWrong:false, sentence:'위로 던진 순간부터 중력이 작용하여 공은 계속 아래 방향 가속도를 받는다', difficulty:2 },
  { misconceptionId:'I1',  isWrong:true,  sentence:'야구공을 치면 배트의 힘이 공 안에 담겨 공이 날아간다', difficulty:2 },
  { misconceptionId:'I1',  isWrong:false, sentence:'배트가 공에 가하는 힘은 접촉 중에만 작용하고 공이 떠난 후에는 힘이 없다', difficulty:2 },
  { misconceptionId:'I5',  isWrong:true,  sentence:'원형 튜브 안을 구르던 구슬은 튜브를 벗어난 후에도 곡선 경로를 따른다', difficulty:3 },
  { misconceptionId:'I5',  isWrong:false, sentence:'원형 경로를 따르던 물체는 구속이 풀리면 그 순간 접선 방향 직선 운동을 한다', difficulty:3 },
  { misconceptionId:'Ob',  isWrong:true,  sentence:'정지한 바닥은 그 위에 있는 물체에 힘을 가하지 않는다', difficulty:1 },
  { misconceptionId:'Ob',  isWrong:false, sentence:'바닥은 그 위의 물체에 수직항력을 가해 중력과 균형을 이룬다', difficulty:1 },
  { misconceptionId:'R1',  isWrong:true,  sentence:'질량이 클수록 물체는 더 쉽게 멈추려 한다', difficulty:2 },
  { misconceptionId:'R1',  isWrong:false, sentence:'질량은 관성(운동 상태를 유지하려는 성질)의 척도이며 멈추려는 성질이 아니다', difficulty:2 },
  { misconceptionId:'R2',  isWrong:true,  sentence:'힘이 마찰력보다 클 때만 물체가 움직일 수 있다', difficulty:2 },
  { misconceptionId:'R2',  isWrong:false, sentence:'알짜힘이 0이어도 이미 운동 중인 물체는 등속으로 계속 움직인다', difficulty:2 },
  // 역학적 에너지 보존 (unit 2)
  { misconceptionId:'ME1',  isWrong:true,  sentence:'미끄럼틀의 경로가 길어 가속이 더 잘되므로 경로가 긴 쪽이 바닥에서 더 큰 속력을 갖는다', difficulty:2 },
  { misconceptionId:'ME1',  isWrong:true,  sentence:'경사가 일정한 미끄럼틀이 가속이 더 잘되므로 그쪽에서 더 큰 속력을 갖는다', difficulty:2 },
  { misconceptionId:'ME1',  isWrong:false, sentence:'마찰이 없다면 경로가 달라도 같은 높이에서 출발해 같은 높이에 도달하면 속력은 같다', difficulty:2 },
  { misconceptionId:'ME2',  isWrong:true,  sentence:'아래 방향으로 던진 공이 위로 던진 공보다 바닥에서 더 빠르다', difficulty:2 },
  { misconceptionId:'ME2',  isWrong:false, sentence:'같은 높이에서 같은 속력으로 던지면 방향과 무관하게 바닥에서의 속력은 같다', difficulty:2 },
  { misconceptionId:'ME4',  isWrong:true,  sentence:'선운동량과 운동에너지가 모두 보존되므로 공을 던진 후에도 사람은 움직이지 않는다', difficulty:3 },
  { misconceptionId:'ME4',  isWrong:false, sentence:'운동량이 보존되므로 공을 던진 사람은 던진 반대 방향으로 움직인다', difficulty:3 },
  { misconceptionId:'ME5',  isWrong:true,  sentence:'무거운 물체가 가벼운 물체보다 아래 방향으로 더 가속되어 바닥에서 속력이 더 크다', difficulty:2 },
  { misconceptionId:'ME5',  isWrong:false, sentence:'마찰이 없다면 질량과 무관하게 같은 높이에서 내려온 물체들의 바닥 속력은 같다', difficulty:2 },
  { misconceptionId:'ME8',  isWrong:true,  sentence:'물체가 2배 먼 거리를 이동했으므로 운동에너지도 2배이다', difficulty:2 },
  { misconceptionId:'ME8',  isWrong:false, sentence:'속력이 2배이면 운동에너지는 속력의 제곱에 비례하므로 4배가 된다', difficulty:3 },
  { misconceptionId:'ME9',  isWrong:true,  sentence:'높이 차이와 절대 높이를 혼동해 위치에너지가 2배라고 판단한다', difficulty:2 },
  { misconceptionId:'ME9',  isWrong:false, sentence:'위치에너지는 질량과 기준면으로부터의 높이의 곱에 비례하므로 높이가 3배면 위치에너지도 3배이다', difficulty:2 },
  { misconceptionId:'ME10', isWrong:true,  sentence:'운동에너지가 움직여야 위치에너지가 움직인다', difficulty:2 },
  { misconceptionId:'ME10', isWrong:true,  sentence:'위치에 따라 빨라지거나 느려진다고만 말할 뿐 에너지 전환은 언급하지 않는다', difficulty:2 },
  { misconceptionId:'ME10', isWrong:false, sentence:'위치에너지가 감소하는 만큼 운동에너지가 증가하며 그 합인 역학적에너지는 일정하다', difficulty:2 },
  { misconceptionId:'ME11', isWrong:true,  sentence:'위치에너지와 운동에너지는 항상 반비례하므로 높이가 높아질수록 운동에너지는 줄어들기만 한다', difficulty:3 },
  { misconceptionId:'ME11', isWrong:false, sentence:'한 지점에서는 위치·운동에너지가 반비례 관계이지만, 초기 높이가 높을수록 최저점에서의 운동에너지는 더 커진다', difficulty:3 },
  { misconceptionId:'ME12', isWrong:true,  sentence:'높이가 높을수록 속력이 빠르다', difficulty:1 },
  { misconceptionId:'ME12', isWrong:false, sentence:'운동에너지는 속력의 제곱에 비례하는 물리량으로 속력 자체와는 다르다', difficulty:2 },
  { misconceptionId:'ME13', isWrong:true,  sentence:'진자의 현재 위치만 보고 판단할 뿐 처음에 놓은 높이는 고려하지 않는다', difficulty:2 },
  { misconceptionId:'ME13', isWrong:false, sentence:'초기 높이가 높을수록 전체 역학적에너지가 크고 최저점에서의 속력도 커진다', difficulty:2 },
  // 파동의 간섭 (unit 4)
  { misconceptionId:'WI1',  isWrong:true,  sentence:'진폭이란 매질의 변위(m)를 의미한다', difficulty:2 },
  { misconceptionId:'WI1',  isWrong:false, sentence:'소리 간섭에서 말하는 진폭은 음압의 진폭(Pa)이다', difficulty:2 },
  { misconceptionId:'WI2',  isWrong:true,  sentence:'마주보는 두 스피커 정중앙에서는 매질이 서로 반대 방향으로 진동하므로 상쇄간섭이 일어난다', difficulty:3 },
  { misconceptionId:'WI2',  isWrong:false, sentence:'두 음원으로부터 거리차가 없어 위상차 없이 만나므로 정중앙에서는 보강간섭이 일어난다', difficulty:3 },

  // 운동량 (unit 2)
  { misconceptionId:'MO1', isWrong:true,  sentence:'충돌 후 질량이 큰 물체가 더 빠르게 움직인다', difficulty:2 },
  { misconceptionId:'MO1', isWrong:true,  sentence:'무거운 공이 가벼운 공과 충돌하면 충돌 후 무거운 공의 속도가 더 크다', difficulty:2 },
  { misconceptionId:'MO1', isWrong:false, sentence:'충돌 후 각 물체의 속도는 운동량 보존 법칙으로 결정되며 질량이 클수록 속도가 크다고 단정할 수 없다', difficulty:3 },
  { misconceptionId:'MO1', isWrong:false, sentence:'운동량 보존에 의해 충돌 전후 전체 운동량의 합은 같으며, 속도는 질량에 반비례하는 경향이 있다', difficulty:3 },
  { misconceptionId:'MO2', isWrong:true,  sentence:'두 물체가 충돌하여 합쳐지면 전체 운동량이 줄어든다', difficulty:2 },
  { misconceptionId:'MO2', isWrong:false, sentence:'완전비탄성충돌에서도 외력이 없으면 충돌 전후 총 운동량은 보존된다', difficulty:2 },
  { misconceptionId:'MO3', isWrong:true,  sentence:'운동량이 큰 물체는 가속도도 크다', difficulty:2 },
  { misconceptionId:'MO3', isWrong:false, sentence:'가속도는 알짜힘을 질량으로 나눈 값(a=F/m)으로 운동량의 크기와 직접적 관계가 없다', difficulty:2 },

  // 전기 회로 (unit 3)
  { misconceptionId:'EC1', isWrong:true,  sentence:'직렬 회로에서 전지에서 멀리 있는 전구일수록 더 어둡게 빛난다', difficulty:2 },
  { misconceptionId:'EC1', isWrong:true,  sentence:'직렬 연결된 두 전구 중 첫 번째 전구가 더 많은 전류를 사용한다', difficulty:2 },
  { misconceptionId:'EC1', isWrong:false, sentence:'직렬 회로에서 전류는 모든 소자에서 동일하며 소자는 전류가 아닌 전기에너지를 소비한다', difficulty:2 },
  { misconceptionId:'EC1', isWrong:false, sentence:'직렬 연결에서 각 전구의 밝기는 위치가 아닌 저항 크기에 따라 결정된다', difficulty:2 },
  { misconceptionId:'EC2', isWrong:true,  sentence:'전압이 클수록 전류도 반드시 크다', difficulty:1 },
  { misconceptionId:'EC2', isWrong:true,  sentence:'전압과 전류는 같은 개념이므로 단위만 다를 뿐이다', difficulty:2 },
  { misconceptionId:'EC2', isWrong:false, sentence:'전압은 전기적 위치에너지 차이이고, 전류는 단위 시간당 이동하는 전하량으로 서로 다른 물리량이다', difficulty:2 },
  { misconceptionId:'EC2', isWrong:false, sentence:'전류의 크기는 전압뿐 아니라 저항에도 의존한다 (I=V/R)', difficulty:2 },
  { misconceptionId:'EC3', isWrong:true,  sentence:'저항을 병렬로 더 연결할수록 전체 저항이 증가한다', difficulty:2 },
  { misconceptionId:'EC3', isWrong:false, sentence:'저항을 병렬로 연결하면 전류 경로가 늘어나 전체 저항은 각 저항보다 작아진다', difficulty:2 },
  { misconceptionId:'EC4', isWrong:true,  sentence:'회로에서 전지와 멀리 떨어진 전구에는 전류가 더 약하게 흐른다', difficulty:2 },
  { misconceptionId:'EC4', isWrong:false, sentence:'이상적인 도선에서 전류는 위치에 관계없이 일정하게 흐른다', difficulty:2 },
  { misconceptionId:'EC5', isWrong:true,  sentence:'전류는 전자가 이동하는 방향과 같은 방향으로 흐른다', difficulty:2 },
  { misconceptionId:'EC5', isWrong:false, sentence:'전류의 방향은 양전하 이동 방향으로 정의되므로 전자 이동 방향의 반대이다', difficulty:2 },
  { misconceptionId:'EC6', isWrong:true,  sentence:'저항이 크면 전류가 전혀 흐르지 않는다', difficulty:1 },
  { misconceptionId:'EC6', isWrong:false, sentence:'저항은 전류를 방해하지만 차단하지는 않는다. 전류는 I=V/R 로 저항에 반비례하여 흐른다', difficulty:2 },

  // 자기장 (unit 3)
  { misconceptionId:'MF1', isWrong:true,  sentence:'직선 도선에 전류가 흐를 때 자기장은 전류 방향과 평행하게 형성된다', difficulty:2 },
  { misconceptionId:'MF1', isWrong:false, sentence:'직선 도선 주변의 자기장은 전류 방향에 수직한 동심원 형태로 형성된다', difficulty:2 },
  { misconceptionId:'MF2', isWrong:true,  sentence:'도선에서 거리가 멀어져도 자기장의 세기는 변하지 않는다', difficulty:2 },
  { misconceptionId:'MF2', isWrong:false, sentence:'직선 도선에서 자기장의 세기는 거리에 반비례하여 멀수록 약해진다 (B ∝ 1/r)', difficulty:2 },
  { misconceptionId:'MF3', isWrong:true,  sentence:'같은 방향으로 전류가 흐르는 두 평행 도선은 서로 밀어낸다', difficulty:2 },
  { misconceptionId:'MF3', isWrong:false, sentence:'같은 방향으로 전류가 흐르는 두 평행 도선 사이에는 인력(당기는 힘)이 작용한다', difficulty:2 },
  { misconceptionId:'MF4', isWrong:true,  sentence:'자기력선은 N극에서만 나오며 S극으로는 들어가지 않는다', difficulty:2 },
  { misconceptionId:'MF4', isWrong:false, sentence:'자기력선은 N극에서 나와 S극으로 들어가는 연속된 닫힌 곡선이다', difficulty:2 },
  { misconceptionId:'MF5', isWrong:true,  sentence:'코일에 전류가 흐를 때 내부 자기장 방향은 전류가 흐르는 방향과 같다', difficulty:2 },
  { misconceptionId:'MF5', isWrong:false, sentence:'코일 내부 자기장 방향은 오른손 법칙으로 결정한다. 전류 방향으로 손가락을 감으면 엄지가 N극 방향이다', difficulty:2 },
  { misconceptionId:'MF6', isWrong:true,  sentence:'전류를 2배로 늘려도 자기장의 세기는 2배가 되지 않는다', difficulty:2 },
  { misconceptionId:'MF6', isWrong:false, sentence:'직선 도선에서 자기장의 세기는 전류에 비례하므로 전류가 2배이면 자기장도 2배이다', difficulty:2 },
  { misconceptionId:'MF7', isWrong:true,  sentence:'전자석과 영구자석의 자기장은 완전히 다른 원리로 발생한다', difficulty:3 },
  { misconceptionId:'MF7', isWrong:false, sentence:'영구자석의 자기장도 원자 내 전자의 운동(전류)에서 비롯되므로 전자석과 같은 근본 원리를 갖는다', difficulty:3 },

  // 전자기 유도 (unit 3)
  { misconceptionId:'EMI1', isWrong:true,  sentence:'자석을 코일 가까이 가져다 놓고 움직이지 않아도 코일에 전류가 흐른다', difficulty:2 },
  { misconceptionId:'EMI1', isWrong:true,  sentence:'강한 자석을 코일 근처에 두기만 해도 유도 전류가 발생한다', difficulty:2 },
  { misconceptionId:'EMI1', isWrong:false, sentence:'전자기 유도는 자기선속의 변화가 있을 때만 발생한다. 자석이 정지해 있으면 전류가 흐르지 않는다', difficulty:2 },
  { misconceptionId:'EMI1', isWrong:false, sentence:'유도 전류가 흐르려면 자석이 움직이거나 코일이 움직여 자기선속이 변해야 한다', difficulty:2 },
  { misconceptionId:'EMI2', isWrong:true,  sentence:'자기장이 강할수록 유도 기전력도 크다', difficulty:2 },
  { misconceptionId:'EMI2', isWrong:false, sentence:'유도 기전력의 크기는 자기장의 세기가 아닌 자기선속의 변화율(ΔΦ/Δt)에 비례한다', difficulty:3 },
  { misconceptionId:'EMI3', isWrong:true,  sentence:'코일 양 끝이 연결되어 있지 않아도 자석을 움직이면 전류가 흐른다', difficulty:2 },
  { misconceptionId:'EMI3', isWrong:false, sentence:'유도 전류가 흐르려면 폐회로가 형성되어야 한다. 개방 회로에서는 기전력이 생겨도 전류는 흐르지 않는다', difficulty:2 },
  { misconceptionId:'EMI4', isWrong:true,  sentence:'N극을 코일에 가까이 할 때 유도 전류의 방향은 N극이 향하는 방향과 같다', difficulty:3 },
  { misconceptionId:'EMI4', isWrong:false, sentence:'유도 전류의 방향은 렌츠의 법칙으로 결정된다. 자속 변화를 방해하는 방향으로 유도 전류가 흐른다', difficulty:3 },
  { misconceptionId:'EMI5', isWrong:true,  sentence:'유도 전류는 항상 원래 자기장을 완전히 없애는 방향으로 흐른다', difficulty:3 },
  { misconceptionId:'EMI5', isWrong:false, sentence:'렌츠의 법칙은 유도 전류가 자속 변화를 방해하는 방향을 의미할 뿐, 자기장을 완전히 상쇄하지는 않는다', difficulty:3 },

  // 원자 모형 (unit 3)
  { misconceptionId:'AT1', isWrong:true,  sentence:'수소 원자의 선 스펙트럼에서 각 선은 원자 안에 있는 서로 다른 종류의 입자를 나타낸다', difficulty:2 },
  { misconceptionId:'AT1', isWrong:false, sentence:'선 스펙트럼의 각 선은 전자가 에너지 준위 사이를 전이할 때 방출하는 빛의 파장을 나타낸다', difficulty:2 },
  { misconceptionId:'AT2', isWrong:true,  sentence:'스펙트럼에 선이 많을수록 원자 안의 전자 수가 많다', difficulty:2 },
  { misconceptionId:'AT2', isWrong:false, sentence:'스펙트럼 선은 전자가 높은 에너지 준위에서 낮은 준위로 전이할 때 방출되는 빛으로, 두 준위의 에너지 차이가 선의 파장을 결정한다', difficulty:3 },
  { misconceptionId:'AT3', isWrong:true,  sentence:'원자 내 전자는 어떤 에너지 값이든 가질 수 있다', difficulty:2 },
  { misconceptionId:'AT3', isWrong:false, sentence:'원자 내 전자는 특정 에너지 값(에너지 준위)만 가질 수 있으며, 그 사이 에너지는 가질 수 없다', difficulty:2 },
  { misconceptionId:'AT4', isWrong:true,  sentence:'오비탈은 전자가 실제로 원운동하는 경로이다', difficulty:2 },
  { misconceptionId:'AT4', isWrong:false, sentence:'오비탈은 전자가 발견될 확률 분포를 나타내는 것으로, 전자가 도는 궤도가 아니다', difficulty:2 },
  { misconceptionId:'AT5', isWrong:true,  sentence:'전자구름 그림에서 점의 개수가 그 위치에 있는 전자의 수를 나타낸다', difficulty:2 },
  { misconceptionId:'AT5', isWrong:false, sentence:'점밀도 그림의 점은 전자가 그 위치에서 발견될 확률의 상대적 크기를 나타내며 전자 개수를 의미하지 않는다', difficulty:2 },
  { misconceptionId:'AT6', isWrong:true,  sentence:'전자가 원자핵에서 멀수록 에너지 준위가 높다', difficulty:2 },
  { misconceptionId:'AT6', isWrong:true,  sentence:'같은 거리에 있는 전자들은 모두 같은 에너지 준위를 가진다', difficulty:3 },
  { misconceptionId:'AT6', isWrong:false, sentence:'현대 원자 모형에서 전자의 에너지는 주양자수(n) 외에 여러 양자수로 결정되며 단순한 거리와 1:1 대응이 아니다', difficulty:3 },

  // 에너지 띠와 반도체 (unit 3)
  { misconceptionId:'EB1', isWrong:true,  sentence:'고체의 에너지 띠는 원자 에너지 준위와 완전히 다른 새로운 개념이다', difficulty:3 },
  { misconceptionId:'EB1', isWrong:false, sentence:'고체에서 수많은 원자의 에너지 준위들이 매우 촘촘하게 모여 거의 연속적인 에너지 띠를 형성한다', difficulty:3 },
  { misconceptionId:'EB2', isWrong:true,  sentence:'반도체는 전기가 잘 흐르지 않는 불완전한 도체일 뿐이다', difficulty:2 },
  { misconceptionId:'EB2', isWrong:false, sentence:'도체·반도체·절연체의 차이는 전도띠와 원자가띠 사이의 에너지 간격(띠 간격) 크기로 설명된다', difficulty:3 },
  { misconceptionId:'EB3', isWrong:true,  sentence:'반도체에 불순물을 첨가하면 새로운 전하가 만들어진다', difficulty:3 },
  { misconceptionId:'EB3', isWrong:false, sentence:'도핑은 자유 전자나 양공의 수를 늘리는 것이며 전체 전하량은 보존된다', difficulty:3 },

  // 파동·굴절 (unit 4)
  { misconceptionId:'WR1', isWrong:true,  sentence:'빛이 물에서 공기로 진행할 때 방향만 바뀌고 속도는 그대로이다', difficulty:2 },
  { misconceptionId:'WR1', isWrong:false, sentence:'빛이 굴절하는 것은 매질에 따라 빛의 속도가 달라지기 때문이다 (v=c/n)', difficulty:2 },
  { misconceptionId:'WR2', isWrong:true,  sentence:'굴절각이 클수록 그 매질에서 빛의 속도가 빠르다는 뜻이다', difficulty:3 },
  { misconceptionId:'WR2', isWrong:false, sentence:'빛의 속도는 굴절각이 아닌 매질의 굴절률로 결정된다 (v=c/n)', difficulty:3 },
  { misconceptionId:'WR3', isWrong:true,  sentence:'전반사는 빛이 어떤 각도로 입사해도 일어날 수 있다', difficulty:2 },
  { misconceptionId:'WR3', isWrong:false, sentence:'전반사는 빛이 굴절률이 큰 매질에서 작은 매질로 진행할 때 입사각이 임계각보다 클 경우에만 일어난다', difficulty:2 },
  { misconceptionId:'WR4', isWrong:true,  sentence:'빛이 굴절할 때 진동수와 파장 모두 변하지 않는다', difficulty:2 },
  { misconceptionId:'WR4', isWrong:false, sentence:'빛이 다른 매질로 진행할 때 진동수는 변하지 않지만, 속도가 변하므로 파장(λ=v/f)도 변한다', difficulty:2 },

  // 빛의 이중성 (unit 4)
  { misconceptionId:'LD1', isWrong:true,  sentence:'더 밝은 빛을 쬐면 튀어나오는 광전자의 운동에너지가 커진다', difficulty:2 },
  { misconceptionId:'LD1', isWrong:true,  sentence:'빛의 세기가 강할수록 광전자가 더 빠른 속도로 튀어나온다', difficulty:2 },
  { misconceptionId:'LD1', isWrong:false, sentence:'광전자의 최대 운동에너지는 빛의 진동수에만 의존하며 빛의 세기와 무관하다 (Ek = hf - W)', difficulty:2 },
  { misconceptionId:'LD1', isWrong:false, sentence:'빛의 세기가 강하면 광전자의 수가 늘어날 뿐, 각 광전자의 에너지는 변하지 않는다', difficulty:3 },
  { misconceptionId:'LD2', isWrong:true,  sentence:'빛은 항상 파동성과 입자성을 동시에 나타낸다', difficulty:2 },
  { misconceptionId:'LD2', isWrong:false, sentence:'빛은 관찰 방식에 따라 파동성(간섭·회절)이나 입자성(광전효과)으로 나타나며 두 성질이 동시에 관측되지 않는다', difficulty:3 },
  { misconceptionId:'LD3', isWrong:true,  sentence:'드브로이 파장이 클수록 더 크고 무거운 입자이다', difficulty:3 },
  { misconceptionId:'LD3', isWrong:false, sentence:'드브로이 파장은 λ=h/mv 로 운동량에 반비례하며 입자의 크기와는 무관하다', difficulty:3 },
  { misconceptionId:'LD4', isWrong:true,  sentence:'빛의 간섭과 회절은 빛이 입자이기 때문에 나타나는 현상이다', difficulty:2 },
  { misconceptionId:'LD4', isWrong:false, sentence:'간섭과 회절은 파동의 특성으로 빛의 파동성을 보여주는 현상이다', difficulty:2 },
];

/* ============================================================
   5. SCORING KEYWORDS
   ============================================================ */
const keywords = [
  { misconceptionId:'I3',  keyword:'등속 운동',       isCorrect:true  },
  { misconceptionId:'I3',  keyword:'알짜힘',          isCorrect:true  },
  { misconceptionId:'I3',  keyword:'뉴턴 제1법칙',    isCorrect:true  },
  { misconceptionId:'I3',  keyword:'관성',            isCorrect:true  },
  { misconceptionId:'I3',  keyword:'힘이 필요',       isCorrect:false },
  { misconceptionId:'I3',  keyword:'계속 밀어야',     isCorrect:false },
  { misconceptionId:'AR1', keyword:'작용-반작용',     isCorrect:true  },
  { misconceptionId:'AR1', keyword:'같은 크기',       isCorrect:true  },
  { misconceptionId:'AR1', keyword:'뉴턴 제3법칙',   isCorrect:true  },
  { misconceptionId:'AR1', keyword:'질량이 클수록',   isCorrect:false },
  { misconceptionId:'AR2', keyword:'뉴턴 제3법칙',   isCorrect:true  },
  { misconceptionId:'AR2', keyword:'능동성 무관',     isCorrect:true  },
  { misconceptionId:'AR2', keyword:'움직이는 쪽이 더 큰', isCorrect:false },
  { misconceptionId:'K1',  keyword:'위치 변화율',     isCorrect:true  },
  { misconceptionId:'K1',  keyword:'독립적',          isCorrect:true  },
  { misconceptionId:'K1',  keyword:'높으면 빠르다',   isCorrect:false },
  { misconceptionId:'K2',  keyword:'속도 변화율',     isCorrect:true  },
  { misconceptionId:'K2',  keyword:'가속도 0',        isCorrect:true  },
  { misconceptionId:'K2',  keyword:'속도와 가속도 같다', isCorrect:false },
  { misconceptionId:'K3',  keyword:'벡터 합',         isCorrect:true  },
  { misconceptionId:'K3',  keyword:'방향 고려',       isCorrect:true  },
  { misconceptionId:'K3',  keyword:'크기만 더하면',   isCorrect:false },
  { misconceptionId:'AF1', keyword:'수직항력',        isCorrect:true  },
  { misconceptionId:'AF1', keyword:'접촉력',          isCorrect:true  },
  { misconceptionId:'AF1', keyword:'정지하면 힘 없다',isCorrect:false },
  { misconceptionId:'AF2', keyword:'알짜힘 0',        isCorrect:true  },
  { misconceptionId:'AF2', keyword:'등속',            isCorrect:true  },
  { misconceptionId:'AF2', keyword:'움직이면 힘 있다',isCorrect:false },
  { misconceptionId:'AF3', keyword:'알짜힘이 0',      isCorrect:true  },
  { misconceptionId:'AF3', keyword:'수직항력',        isCorrect:true  },
  { misconceptionId:'AF3', keyword:'힘이 없다',       isCorrect:false },
  { misconceptionId:'AF4', keyword:'가속도 비례',     isCorrect:true  },
  { misconceptionId:'AF4', keyword:'F=ma',           isCorrect:true  },
  { misconceptionId:'AF4', keyword:'속도 비례',       isCorrect:false },
  { misconceptionId:'AF5', keyword:'일정한 가속도',   isCorrect:true  },
  { misconceptionId:'AF5', keyword:'힘도 증가',       isCorrect:false },
  { misconceptionId:'CI1', keyword:'벡터 합',         isCorrect:true  },
  { misconceptionId:'CI1', keyword:'알짜힘',          isCorrect:true  },
  { misconceptionId:'CI1', keyword:'가장 큰 힘',      isCorrect:false },
  { misconceptionId:'CF',  keyword:'구심력',          isCorrect:true  },
  { misconceptionId:'CF',  keyword:'관성계',          isCorrect:true  },
  { misconceptionId:'CF',  keyword:'원심력 실재',     isCorrect:false },
  { misconceptionId:'G3',  keyword:'중력가속도 일정', isCorrect:true  },
  { misconceptionId:'G3',  keyword:'질량 무관',       isCorrect:true  },
  { misconceptionId:'G3',  keyword:'무거울수록',      isCorrect:false },
  { misconceptionId:'G4',  keyword:'g 일정',          isCorrect:true  },
  { misconceptionId:'G4',  keyword:'낙하할수록 커진다',isCorrect:false },
  { misconceptionId:'G5',  keyword:'항상 작용',       isCorrect:true  },
  { misconceptionId:'G5',  keyword:'최고점 이후',     isCorrect:false },
  { misconceptionId:'Ob',  keyword:'수직항력',        isCorrect:true  },
  { misconceptionId:'Ob',  keyword:'정지하면 힘 없음',isCorrect:false },
  { misconceptionId:'R1',  keyword:'관성',            isCorrect:true  },
  { misconceptionId:'R1',  keyword:'마찰',            isCorrect:true  },
  { misconceptionId:'R1',  keyword:'멈추려 한다',     isCorrect:false },
];

/* ============================================================
   6. FCI / FMCE ITEMS  (FMCE 43개 + FCI 30개)
   ============================================================ */
const fciItems = [
  // ── FMCE Force Sled (Q1-7) ──
  { id:'FMCE-1',  source:'FMCE', questionNo:1,  group:'Force Sled', correctAnswer:'B', unitId:'1',
    text:'썰매가 오른쪽으로 이동하면서 일정한 비율로 빨라지고 있다. 어떤 힘이 이 운동을 유지하는가?',
    choices:{A:'오른쪽 방향, 힘이 증가',B:'오른쪽 방향, 힘이 일정',C:'오른쪽 방향, 힘이 감소',D:'힘 없음',E:'왼쪽 방향, 힘이 증가',F:'왼쪽 방향, 힘이 일정',G:'왼쪽 방향, 힘이 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-2',  source:'FMCE', questionNo:2,  group:'Force Sled', correctAnswer:'D', unitId:'1',
    text:'썰매가 오른쪽으로 일정한 속도(등속)로 이동하고 있다. 어떤 힘이 이 운동을 유지하는가?',
    choices:{A:'오른쪽 방향, 힘이 증가',B:'오른쪽 방향, 힘이 일정',C:'오른쪽 방향, 힘이 감소',D:'힘 없음',E:'왼쪽 방향, 힘이 증가',F:'왼쪽 방향, 힘이 일정',G:'왼쪽 방향, 힘이 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-3',  source:'FMCE', questionNo:3,  group:'Force Sled', correctAnswer:'F', unitId:'1',
    text:'썰매가 오른쪽으로 이동하면서 일정한 비율로 느려지고 있다. 어떤 힘이 이 운동을 유지하는가?',
    choices:{A:'오른쪽 방향, 힘이 증가',B:'오른쪽 방향, 힘이 일정',C:'오른쪽 방향, 힘이 감소',D:'힘 없음',E:'왼쪽 방향, 힘이 증가',F:'왼쪽 방향, 힘이 일정',G:'왼쪽 방향, 힘이 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-4',  source:'FMCE', questionNo:4,  group:'Force Sled', correctAnswer:'F', unitId:'1',
    text:'썰매가 왼쪽으로 이동하면서 일정한 비율로 빨라지고 있다. 어떤 힘이 이 운동을 유지하는가?',
    choices:{A:'오른쪽 방향, 힘이 증가',B:'오른쪽 방향, 힘이 일정',C:'오른쪽 방향, 힘이 감소',D:'힘 없음',E:'왼쪽 방향, 힘이 증가',F:'왼쪽 방향, 힘이 일정',G:'왼쪽 방향, 힘이 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-5',  source:'FMCE', questionNo:5,  group:'Force Sled', correctAnswer:'D', unitId:'1',
    text:'썰매를 정지 상태에서 밀어 오른쪽으로 일정한 속도에 도달시켰다. 이 속도를 유지하려면 어떤 힘이 필요한가?',
    choices:{A:'오른쪽 방향, 힘이 증가',B:'오른쪽 방향, 힘이 일정',C:'오른쪽 방향, 힘이 감소',D:'힘 없음',E:'왼쪽 방향, 힘이 증가',F:'왼쪽 방향, 힘이 일정',G:'왼쪽 방향, 힘이 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-6',  source:'FMCE', questionNo:6,  group:'Force Sled', correctAnswer:'B', unitId:'1',
    text:'썰매가 일정한 비율로 느려지고 있으며 가속도 방향은 오른쪽이다. 어떤 힘이 이 운동을 설명하는가?',
    choices:{A:'오른쪽 방향, 힘이 증가',B:'오른쪽 방향, 힘이 일정',C:'오른쪽 방향, 힘이 감소',D:'힘 없음',E:'왼쪽 방향, 힘이 증가',F:'왼쪽 방향, 힘이 일정',G:'왼쪽 방향, 힘이 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-7',  source:'FMCE', questionNo:7,  group:'Force Sled', correctAnswer:'B', unitId:'1',
    text:'썰매가 왼쪽으로 이동하면서 일정한 비율로 느려지고 있다. 어떤 힘이 이 운동을 유지하는가?',
    choices:{A:'오른쪽 방향, 힘이 증가',B:'오른쪽 방향, 힘이 일정',C:'오른쪽 방향, 힘이 감소',D:'힘 없음',E:'왼쪽 방향, 힘이 증가',F:'왼쪽 방향, 힘이 일정',G:'왼쪽 방향, 힘이 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  // ── FMCE Cart on Ramp (Q8-10) ──
  { id:'FMCE-8',  source:'FMCE', questionNo:8,  group:'Cart on Ramp', correctAnswer:'A', unitId:'1',
    text:'장난감 자동차를 경사면 위로 밀어 올렸다. 놓은 후 위로 올라가는 동안 자동차에 작용하는 알짜힘은?',
    choices:{A:'경사면 아래 방향, 일정',B:'경사면 아래 방향, 증가',C:'경사면 아래 방향, 감소',D:'힘 없음',E:'경사면 위 방향, 일정',F:'경사면 위 방향, 증가',G:'경사면 위 방향, 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-9',  source:'FMCE', questionNo:9,  group:'Cart on Ramp', correctAnswer:'A', unitId:'1',
    text:'장난감 자동차가 경사면 최고점에 있을 때 자동차에 작용하는 알짜힘은?',
    choices:{A:'경사면 아래 방향, 일정',B:'경사면 아래 방향, 증가',C:'경사면 아래 방향, 감소',D:'힘 없음',E:'경사면 위 방향, 일정',F:'경사면 위 방향, 증가',G:'경사면 위 방향, 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-10', source:'FMCE', questionNo:10, group:'Cart on Ramp', correctAnswer:'A', unitId:'1',
    text:'장난감 자동차가 경사면을 내려오는 동안 자동차에 작용하는 알짜힘은?',
    choices:{A:'경사면 아래 방향, 일정',B:'경사면 아래 방향, 증가',C:'경사면 아래 방향, 감소',D:'힘 없음',E:'경사면 위 방향, 일정',F:'경사면 위 방향, 증가',G:'경사면 위 방향, 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  // ── FMCE Coin Toss (Q11-13) ──
  { id:'FMCE-11', source:'FMCE', questionNo:11, group:'Coin Toss', correctAnswer:'A', unitId:'1',
    text:'동전을 위로 던졌다. 손을 떠난 후 위로 올라가는 동안 동전에 작용하는 힘은? (공기저항 무시)',
    choices:{A:'아래 방향, 일정',B:'아래 방향, 증가',C:'아래 방향, 감소',D:'힘 없음',E:'위 방향, 일정',F:'위 방향, 증가',G:'위 방향, 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-12', source:'FMCE', questionNo:12, group:'Coin Toss', correctAnswer:'A', unitId:'1',
    text:'동전을 위로 던졌다. 동전이 최고점에 있을 때 동전에 작용하는 힘은? (공기저항 무시)',
    choices:{A:'아래 방향, 일정',B:'아래 방향, 증가',C:'아래 방향, 감소',D:'힘 없음',E:'위 방향, 일정',F:'위 방향, 증가',G:'위 방향, 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-13', source:'FMCE', questionNo:13, group:'Coin Toss', correctAnswer:'A', unitId:'1',
    text:'동전을 위로 던졌다. 최고점 이후 아래로 내려오는 동안 동전에 작용하는 힘은? (공기저항 무시)',
    choices:{A:'아래 방향, 일정',B:'아래 방향, 증가',C:'아래 방향, 감소',D:'힘 없음',E:'위 방향, 일정',F:'위 방향, 증가',G:'위 방향, 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  // ── FMCE Force Graph (Q14-21) ──
  { id:'FMCE-14', source:'FMCE', questionNo:14, group:'Force Graph', correctAnswer:'D', unitId:'1',
    text:'장난감 자동차가 오른쪽으로 일정한 속도로 이동하고 있다. 이 운동을 유지하는 힘-시간 그래프는?',
    choices:{A:'양수 일정',B:'양수 증가',C:'양수 감소',D:'0 (힘 없음)',E:'음수 일정',F:'음수 감소',G:'음수 증가',H:'양수 감소 후 음수',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-15', source:'FMCE', questionNo:15, group:'Force Graph', correctAnswer:'D', unitId:'1',
    text:'장난감 자동차가 정지해 있다. 이 상태를 나타내는 힘-시간 그래프는?',
    choices:{A:'양수 일정',B:'양수 증가',C:'양수 감소',D:'0 (힘 없음)',E:'음수 일정',F:'음수 감소',G:'음수 증가',H:'양수 감소 후 음수',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-16', source:'FMCE', questionNo:16, group:'Force Graph', correctAnswer:'A', unitId:'1',
    text:'장난감 자동차가 오른쪽으로 일정한 비율로 빨라지고 있다. 이 운동을 만드는 힘-시간 그래프는?',
    choices:{A:'양수 일정',B:'양수 증가',C:'양수 감소',D:'0 (힘 없음)',E:'음수 일정',F:'음수 감소',G:'음수 증가',H:'양수 감소 후 음수',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-17', source:'FMCE', questionNo:17, group:'Force Graph', correctAnswer:'D', unitId:'1',
    text:'장난감 자동차가 왼쪽으로 일정한 속도로 이동하고 있다. 이 운동을 유지하는 힘-시간 그래프는?',
    choices:{A:'양수 일정',B:'양수 증가',C:'양수 감소',D:'0 (힘 없음)',E:'음수 일정',F:'음수 감소',G:'음수 증가',H:'양수 감소 후 음수',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-18', source:'FMCE', questionNo:18, group:'Force Graph', correctAnswer:'E', unitId:'1',
    text:'장난감 자동차가 오른쪽으로 이동하다 일정한 비율로 느려지고 있다. 이 운동을 만드는 힘-시간 그래프는?',
    choices:{A:'양수 일정',B:'양수 증가',C:'양수 감소',D:'0 (힘 없음)',E:'음수 일정',F:'음수 감소',G:'음수 증가',H:'양수 감소 후 음수',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-19', source:'FMCE', questionNo:19, group:'Force Graph', correctAnswer:'E', unitId:'1',
    text:'장난감 자동차가 왼쪽으로 이동하면서 일정한 비율로 빨라지고 있다. 이 운동을 만드는 힘-시간 그래프는?',
    choices:{A:'양수 일정',B:'양수 증가',C:'양수 감소',D:'0 (힘 없음)',E:'음수 일정',F:'음수 감소',G:'음수 증가',H:'양수 감소 후 음수',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-20', source:'FMCE', questionNo:20, group:'Force Graph', correctAnswer:'J', unitId:'1',
    text:'장난감 자동차가 오른쪽으로 이동하다가 빨라진 후 느려진다. 이 운동을 만드는 힘-시간 그래프는?',
    choices:{A:'양수 일정',B:'양수 증가',C:'양수 감소',D:'0 (힘 없음)',E:'음수 일정',F:'음수 감소',G:'음수 증가',H:'양수 감소 후 음수',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-21', source:'FMCE', questionNo:21, group:'Force Graph', correctAnswer:'D', unitId:'1',
    text:'장난감 자동차를 오른쪽으로 밀었다가 손을 뗐다. 손을 뗀 후의 힘-시간 그래프는?',
    choices:{A:'양수 일정',B:'양수 증가',C:'양수 감소',D:'0 (힘 없음)',E:'음수 일정',F:'음수 감소',G:'음수 증가',H:'양수 감소 후 음수',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  // ── FMCE Acceleration Graph (Q22-26) ──
  { id:'FMCE-22', source:'FMCE', questionNo:22, group:'Acceleration Graph', correctAnswer:'A', unitId:'1',
    text:'장난감 자동차가 오른쪽으로 이동하면서 일정한 비율로 빨라지고 있다. 이 운동에 해당하는 가속도-시간 그래프는?',
    choices:{A:'양수 일정',B:'음수 일정',C:'0',D:'양수 증가',E:'음수 증가',F:'음수 감소',G:'양수 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-23', source:'FMCE', questionNo:23, group:'Acceleration Graph', correctAnswer:'B', unitId:'1',
    text:'장난감 자동차가 오른쪽으로 이동하면서 일정한 비율로 느려지고 있다. 이 운동에 해당하는 가속도-시간 그래프는?',
    choices:{A:'양수 일정',B:'음수 일정',C:'0',D:'양수 증가',E:'음수 증가',F:'음수 감소',G:'양수 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-24', source:'FMCE', questionNo:24, group:'Acceleration Graph', correctAnswer:'C', unitId:'1',
    text:'장난감 자동차가 왼쪽으로 일정한 속도로 이동하고 있다. 이 운동에 해당하는 가속도-시간 그래프는?',
    choices:{A:'양수 일정',B:'음수 일정',C:'0',D:'양수 증가',E:'음수 증가',F:'음수 감소',G:'양수 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-25', source:'FMCE', questionNo:25, group:'Acceleration Graph', correctAnswer:'B', unitId:'1',
    text:'장난감 자동차가 왼쪽으로 이동하면서 일정한 비율로 빨라지고 있다. 이 운동에 해당하는 가속도-시간 그래프는?',
    choices:{A:'양수 일정',B:'음수 일정',C:'0',D:'양수 증가',E:'음수 증가',F:'음수 감소',G:'양수 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-26', source:'FMCE', questionNo:26, group:'Acceleration Graph', correctAnswer:'C', unitId:'1',
    text:'장난감 자동차가 오른쪽으로 일정한 속도로 이동하고 있다. 이 운동에 해당하는 가속도-시간 그래프는?',
    choices:{A:'양수 일정',B:'음수 일정',C:'0',D:'양수 증가',E:'음수 증가',F:'음수 감소',G:'양수 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  // ── FMCE Coin Toss Acceleration (Q27-29) ──
  { id:'FMCE-27', source:'FMCE', questionNo:27, group:'Coin Toss Acceleration', correctAnswer:'A', unitId:'1',
    text:'동전을 위로 던졌다. 손을 떠난 후 위로 올라가는 동안 동전의 가속도는? (위 방향 +)',
    choices:{A:'음수 방향, 일정',B:'음수 방향, 증가',C:'음수 방향, 감소',D:'0',E:'양수 방향, 일정',F:'양수 방향, 증가',G:'양수 방향, 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-28', source:'FMCE', questionNo:28, group:'Coin Toss Acceleration', correctAnswer:'A', unitId:'1',
    text:'동전을 위로 던졌다. 동전이 최고점에 있을 때 동전의 가속도는?',
    choices:{A:'음수 방향, 일정',B:'음수 방향, 증가',C:'음수 방향, 감소',D:'0',E:'양수 방향, 일정',F:'양수 방향, 증가',G:'양수 방향, 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-29', source:'FMCE', questionNo:29, group:'Coin Toss Acceleration', correctAnswer:'A', unitId:'1',
    text:'동전을 위로 던졌다. 최고점 이후 아래로 내려오는 동안 동전의 가속도는?',
    choices:{A:'음수 방향, 일정',B:'음수 방향, 증가',C:'음수 방향, 감소',D:'0',E:'양수 방향, 일정',F:'양수 방향, 증가',G:'양수 방향, 감소',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  // ── FMCE Collision (Q30-34) ──
  { id:'FMCE-30', source:'FMCE', questionNo:30, group:'Collision', correctAnswer:'E', unitId:'1',
    text:'트럭이 자동차보다 훨씬 무겁다. 같은 속도로 달리다 충돌할 때 힘의 크기 관계는?',
    choices:{A:'트럭이 더 큰 힘',B:'자동차가 더 큰 힘',C:'힘 없음',D:'트럭만 힘',E:'두 힘 같음',F:'정보 부족',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-31', source:'FMCE', questionNo:31, group:'Collision', correctAnswer:'E', unitId:'1',
    text:'트럭이 자동차보다 훨씬 무겁다. 자동차가 훨씬 빠를 때 충돌 시 힘의 크기 관계는?',
    choices:{A:'트럭이 더 큰 힘',B:'자동차가 더 큰 힘',C:'힘 없음',D:'트럭만 힘',E:'두 힘 같음',F:'정보 부족',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-32', source:'FMCE', questionNo:32, group:'Collision', correctAnswer:'E', unitId:'1',
    text:'트럭이 자동차보다 훨씬 무겁다. 트럭이 정지해 있을 때 자동차가 충돌 시 힘의 크기 관계는?',
    choices:{A:'트럭이 더 큰 힘',B:'자동차가 더 큰 힘',C:'힘 없음',D:'트럭만 힘',E:'두 힘 같음',F:'정보 부족',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-33', source:'FMCE', questionNo:33, group:'Collision', correctAnswer:'E', unitId:'1',
    text:'트럭과 자동차의 질량이 같다. 같은 속도로 달리다 충돌할 때 힘의 크기 관계는?',
    choices:{A:'트럭이 더 큰 힘',B:'자동차가 더 큰 힘',C:'힘 없음',D:'트럭만 힘',E:'두 힘 같음',F:'정보 부족',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-34', source:'FMCE', questionNo:34, group:'Collision', correctAnswer:'E', unitId:'1',
    text:'트럭과 자동차의 질량이 같다. 트럭이 정지해 있을 때 자동차가 충돌 시 힘의 크기 관계는?',
    choices:{A:'트럭이 더 큰 힘',B:'자동차가 더 큰 힘',C:'힘 없음',D:'트럭만 힘',E:'두 힘 같음',F:'정보 부족',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  // ── FMCE Pushing (Q35-38) ──
  { id:'FMCE-35', source:'FMCE', questionNo:35, group:'Pushing', correctAnswer:'A', unitId:'1',
    text:'소형차가 고장난 트럭을 밀고 있지만 트럭이 움직이지 않는다. 힘의 크기 관계는?',
    choices:{A:'차=트럭',B:'차<트럭',C:'차>트럭',D:'차만 힘',E:'힘 없음',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-36', source:'FMCE', questionNo:36, group:'Pushing', correctAnswer:'A', unitId:'1',
    text:'소형차가 트럭을 밀면서 가속하는 중이다. 힘의 크기 관계는?',
    choices:{A:'차=트럭',B:'차<트럭',C:'차>트럭',D:'차만 힘',E:'힘 없음',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-37', source:'FMCE', questionNo:37, group:'Pushing', correctAnswer:'A', unitId:'1',
    text:'소형차가 트럭을 밀면서 일정한 속도(등속)로 이동 중이다. 힘의 크기 관계는?',
    choices:{A:'차=트럭',B:'차<트럭',C:'차>트럭',D:'차만 힘',E:'힘 없음',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-38', source:'FMCE', questionNo:38, group:'Pushing', correctAnswer:'A', unitId:'1',
    text:'소형차가 트럭을 밀다가 트럭이 브레이크를 밟아 감속 중이다. 힘의 크기 관계는?',
    choices:{A:'차=트럭',B:'차<트럭',C:'차>트럭',D:'차만 힘',E:'힘 없음',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  // ── FMCE Bob & Jim (Q39) ──
  { id:'FMCE-39', source:'FMCE', questionNo:39, group:'Bob and Jim', correctAnswer:'E', unitId:'1',
    text:'Bob(95kg)과 Jim(77kg)이 의자에 앉아 마주보고 있다. Bob이 Jim의 무릎을 발로 밀었을 때 두 학생에게 작용하는 힘은?',
    choices:{A:'아무도 힘 없음',B:'Bob만 힘을 가함',C:'Jim이 더 큰 힘',D:'Bob이 더 큰 힘',E:'두 힘 같음',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  // ── FMCE Velocity Graph (Q40-43) ──
  { id:'FMCE-40', source:'FMCE', questionNo:40, group:'Velocity Graph', correctAnswer:'A', unitId:'1',
    text:'장난감 자동차가 오른쪽으로 일정한 속도로 이동하고 있다. 이 운동에 해당하는 속도-시간 그래프는?',
    choices:{A:'양수 일정',B:'음수 일정',C:'0',D:'양수 증가(선형)',E:'음수 증가',F:'양수→0→음수',G:'음수→0→양수',H:'양수 감소 후 증가',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-41', source:'FMCE', questionNo:41, group:'Velocity Graph', correctAnswer:'F', unitId:'1',
    text:'장난감 자동차가 방향을 바꾸고 있다. 이 운동에 해당하는 속도-시간 그래프는?',
    choices:{A:'양수 일정',B:'음수 일정',C:'0',D:'양수 증가(선형)',E:'음수 증가',F:'양수→0→음수',G:'음수→0→양수',H:'양수 감소 후 증가',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-42', source:'FMCE', questionNo:42, group:'Velocity Graph', correctAnswer:'B', unitId:'1',
    text:'장난감 자동차가 왼쪽으로 일정한 속도로 이동하고 있다. 이 운동에 해당하는 속도-시간 그래프는?',
    choices:{A:'양수 일정',B:'음수 일정',C:'0',D:'양수 증가(선형)',E:'음수 증가',F:'양수→0→음수',G:'음수→0→양수',H:'양수 감소 후 증가',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  { id:'FMCE-43', source:'FMCE', questionNo:43, group:'Velocity Graph', correctAnswer:'D', unitId:'1',
    text:'장난감 자동차가 일정한 비율로 속도가 증가하고 있다. 이 운동에 해당하는 속도-시간 그래프는?',
    choices:{A:'양수 일정',B:'음수 일정',C:'0',D:'양수 증가(선형)',E:'음수 증가',F:'양수→0→음수',G:'음수→0→양수',H:'양수 감소 후 증가',J:'해당 없음'},
    sourcePaper:'Thornton & Sokoloff (1998), Am. J. Phys. 66(4)' },
  // ── FCI (Q1-30) ──
  { id:'FCI-1',  source:'FCI', questionNo:1,  group:'Gravity',      correctAnswer:'C', unitId:'1', choices:{}, text:'FCI 1번: 두 물체를 동시에 같은 높이에서 떨어뜨릴 때 어느 것이 먼저 떨어지는가?',         sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-2',  source:'FCI', questionNo:2,  group:'Newton3',      correctAnswer:'E', unitId:'1', choices:{}, text:'FCI 2번: 무거운 트럭과 가벼운 자동차 정면충돌 시 힘의 관계는?',                           sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-3',  source:'FCI', questionNo:3,  group:'Gravity',      correctAnswer:'A', unitId:'1', choices:{}, text:'FCI 3번: 두 물체를 서로 다른 높이에서 떨어뜨릴 때 낙하 가속도는?',                         sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-4',  source:'FCI', questionNo:4,  group:'Newton1',      correctAnswer:'C', unitId:'1', choices:{}, text:'FCI 4번: 마찰 없는 수평면에서 물체를 밀었다 손을 뗀 후 운동은?',                           sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-5',  source:'FCI', questionNo:5,  group:'Gravity',      correctAnswer:'D', unitId:'1', choices:{}, text:'FCI 5번: 낙하 중인 물체에 작용하는 힘은?',                                                   sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-6',  source:'FCI', questionNo:6,  group:'Newton1',      correctAnswer:'B', unitId:'1', choices:{}, text:'FCI 6번: 등속 운동하는 물체에 작용하는 힘은?',                                               sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-7',  source:'FCI', questionNo:7,  group:'Newton1',      correctAnswer:'E', unitId:'1', choices:{}, text:'FCI 7번: 두 힘이 작용할 때 물체의 운동 방향은?',                                             sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-8',  source:'FCI', questionNo:8,  group:'Newton1',      correctAnswer:'A', unitId:'1', choices:{}, text:'FCI 8번: 마찰 없이 미끄러지는 물체의 운동은?',                                               sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-9',  source:'FCI', questionNo:9,  group:'Superposition',correctAnswer:'D', unitId:'1', choices:{}, text:'FCI 9번: 여러 힘이 작용하는 물체의 운동 방향은?',                                            sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-10', source:'FCI', questionNo:10, group:'Newton1',      correctAnswer:'B', unitId:'1', choices:{}, text:'FCI 10번: 원형 경로에서 구속 해제 후 물체 운동은?',                                          sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-11', source:'FCI', questionNo:11, group:'Newton3',      correctAnswer:'E', unitId:'1', choices:{}, text:'FCI 11번: 충돌 시 작용-반작용 힘은?',                                                        sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-12', source:'FCI', questionNo:12, group:'Force',        correctAnswer:'D', unitId:'1', choices:{}, text:'FCI 12번: 부력이 작용하는 물체에 작용하는 힘은?',                                            sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-13', source:'FCI', questionNo:13, group:'Newton3',      correctAnswer:'A', unitId:'1', choices:{}, text:'FCI 13번: 물체가 밀고 있는 대상에 작용하는 힘은?',                                          sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-14', source:'FCI', questionNo:14, group:'Newton3',      correctAnswer:'A', unitId:'1', choices:{}, text:'FCI 14번: 정지한 물체에 작용하는 힘은?',                                                     sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-15', source:'FCI', questionNo:15, group:'Force',        correctAnswer:'C', unitId:'1', choices:{}, text:'FCI 15번: 스프링으로 밀린 물체에 작용하는 힘은?',                                           sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-16', source:'FCI', questionNo:16, group:'Newton2',      correctAnswer:'B', unitId:'1', choices:{}, text:'FCI 16번: 포물선 운동하는 물체의 중간 지점에서의 힘은?',                                    sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-17', source:'FCI', questionNo:17, group:'Newton2',      correctAnswer:'C', unitId:'1', choices:{}, text:'FCI 17번: 자유낙하 중인 물체의 가속도는?',                                                   sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-18', source:'FCI', questionNo:18, group:'Newton1',      correctAnswer:'B', unitId:'1', choices:{}, text:'FCI 18번: 등속 상승하는 엘리베이터 안 물체의 힘은?',                                        sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-19', source:'FCI', questionNo:19, group:'Superposition',correctAnswer:'B', unitId:'1', choices:{}, text:'FCI 19번: 두 힘이 동시에 작용할 때 물체 방향은?',                                           sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-20', source:'FCI', questionNo:20, group:'Kinematics',   correctAnswer:'E', unitId:'1', choices:{}, text:'FCI 20번: 속도-시간 그래프 해석은?',                                                         sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-21', source:'FCI', questionNo:21, group:'Kinematics',   correctAnswer:'D', unitId:'1', choices:{}, text:'FCI 21번: 가속도-시간 그래프 해석은?',                                                       sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-22', source:'FCI', questionNo:22, group:'Newton2',      correctAnswer:'D', unitId:'1', choices:{}, text:'FCI 22번: 공기저항이 작용하는 물체의 운동은?',                                               sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-23', source:'FCI', questionNo:23, group:'Newton2',      correctAnswer:'D', unitId:'1', choices:{}, text:'FCI 23번: 포물선 경로 최고점에서의 힘은?',                                                   sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-24', source:'FCI', questionNo:24, group:'Newton2',      correctAnswer:'E', unitId:'1', choices:{}, text:'FCI 24번: 일정한 힘이 작용할 때 속도 변화는?',                                               sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-25', source:'FCI', questionNo:25, group:'Newton2',      correctAnswer:'B', unitId:'1', choices:{}, text:'FCI 25번: 일정한 힘 작용 시 물체의 운동은?',                                                 sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-26', source:'FCI', questionNo:26, group:'Newton1',      correctAnswer:'B', unitId:'1', choices:{}, text:'FCI 26번: 힘이 없을 때 물체의 속도 방향은?',                                                 sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-27', source:'FCI', questionNo:27, group:'Newton1',      correctAnswer:'A', unitId:'1', choices:{}, text:'FCI 27번: 힘이 없을 때 물체의 속력은?',                                                      sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-28', source:'FCI', questionNo:28, group:'Newton1',      correctAnswer:'C', unitId:'1', choices:{}, text:'FCI 28번: 상쇄되는 힘이 작용할 때 물체의 운동은?',                                          sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-29', source:'FCI', questionNo:29, group:'Force',        correctAnswer:'C', unitId:'1', choices:{}, text:'FCI 29번: 마찰력의 방향은?',                                                                  sourcePaper:'Hestenes et al. (1992)' },
  { id:'FCI-30', source:'FCI', questionNo:30, group:'Newton3',      correctAnswer:'E', unitId:'1', choices:{}, text:'FCI 30번: 총알과 총에 작용하는 힘의 관계는?',                                                 sourcePaper:'Hestenes et al. (1992)' },
];

/* ============================================================
   7. ITEM-MISCONCEPTION MAP
   ============================================================ */
const itemMap = [
  // FMCE
  { itemId:'FMCE-2',  choice:'B', misconceptionId:'I3'  },
  { itemId:'FMCE-2',  choice:'A', misconceptionId:'AF4' },
  { itemId:'FMCE-5',  choice:'B', misconceptionId:'I3'  },
  { itemId:'FMCE-9',  choice:'D', misconceptionId:'AF3' },
  { itemId:'FMCE-11', choice:'G', misconceptionId:'G5'  },
  { itemId:'FMCE-11', choice:'E', misconceptionId:'I3'  },
  { itemId:'FMCE-12', choice:'D', misconceptionId:'AF3' },
  { itemId:'FMCE-12', choice:'G', misconceptionId:'I3'  },
  { itemId:'FMCE-13', choice:'B', misconceptionId:'G4'  },
  { itemId:'FMCE-27', choice:'D', misconceptionId:'AF3' },
  { itemId:'FMCE-27', choice:'C', misconceptionId:'I3'  },
  { itemId:'FMCE-28', choice:'D', misconceptionId:'AF3' },
  { itemId:'FMCE-29', choice:'D', misconceptionId:'AF3' },
  { itemId:'FMCE-29', choice:'B', misconceptionId:'G4'  },
  { itemId:'FMCE-30', choice:'A', misconceptionId:'AR1' },
  { itemId:'FMCE-31', choice:'B', misconceptionId:'AR2' },
  { itemId:'FMCE-32', choice:'A', misconceptionId:'AR1' },
  { itemId:'FMCE-39', choice:'D', misconceptionId:'AR1' },
  { itemId:'FMCE-39', choice:'C', misconceptionId:'AR2' },
  // FCI Kinematics
  { itemId:'FCI-20', choice:'B', misconceptionId:'K1' },
  { itemId:'FCI-20', choice:'C', misconceptionId:'K1' },
  { itemId:'FCI-20', choice:'D', misconceptionId:'K1' },
  { itemId:'FCI-20', choice:'A', misconceptionId:'K2' },
  { itemId:'FCI-21', choice:'B', misconceptionId:'K2' },
  { itemId:'FCI-21', choice:'C', misconceptionId:'K2' },
  { itemId:'FCI-7',  choice:'C', misconceptionId:'K3' },
  // FCI Impetus
  { itemId:'FCI-9',  choice:'B', misconceptionId:'I1' },
  { itemId:'FCI-9',  choice:'C', misconceptionId:'I1' },
  { itemId:'FCI-4',  choice:'D', misconceptionId:'I2' },
  { itemId:'FCI-6',  choice:'C', misconceptionId:'I2' },
  { itemId:'FCI-5',  choice:'A', misconceptionId:'I3' },
  { itemId:'FCI-5',  choice:'B', misconceptionId:'I3' },
  { itemId:'FCI-5',  choice:'C', misconceptionId:'I3' },
  { itemId:'FCI-8',  choice:'C', misconceptionId:'I3' },
  { itemId:'FCI-6',  choice:'D', misconceptionId:'I4' },
  { itemId:'FCI-8',  choice:'B', misconceptionId:'I4' },
  { itemId:'FCI-8',  choice:'D', misconceptionId:'I4' },
  { itemId:'FCI-4',  choice:'A', misconceptionId:'I5' },
  { itemId:'FCI-4',  choice:'D', misconceptionId:'I5' },
  { itemId:'FCI-10', choice:'A', misconceptionId:'I5' },
  // FCI Active Force
  { itemId:'FCI-11', choice:'B', misconceptionId:'AF1' },
  { itemId:'FCI-12', choice:'B', misconceptionId:'AF1' },
  { itemId:'FCI-13', choice:'D', misconceptionId:'AF1' },
  { itemId:'FCI-14', choice:'D', misconceptionId:'AF1' },
  { itemId:'FCI-15', choice:'A', misconceptionId:'AF1' },
  { itemId:'FCI-15', choice:'B', misconceptionId:'AF1' },
  { itemId:'FCI-29', choice:'A', misconceptionId:'AF2' },
  { itemId:'FCI-12', choice:'E', misconceptionId:'AF3' },
  { itemId:'FCI-25', choice:'A', misconceptionId:'AF4' },
  { itemId:'FCI-28', choice:'A', misconceptionId:'AF4' },
  // FCI Action/Reaction
  { itemId:'FCI-2',  choice:'A', misconceptionId:'AR1' },
  { itemId:'FCI-2',  choice:'D', misconceptionId:'AR1' },
  { itemId:'FCI-11', choice:'D', misconceptionId:'AR1' },
  { itemId:'FCI-13', choice:'B', misconceptionId:'AR1' },
  { itemId:'FCI-14', choice:'B', misconceptionId:'AR1' },
  { itemId:'FCI-13', choice:'C', misconceptionId:'AR2' },
  { itemId:'FCI-14', choice:'C', misconceptionId:'AR2' },
  // FCI Concatenation
  { itemId:'FCI-18', choice:'A', misconceptionId:'CI1' },
  { itemId:'FCI-18', choice:'E', misconceptionId:'CI1' },
  { itemId:'FCI-19', choice:'A', misconceptionId:'CI1' },
  { itemId:'FCI-4',  choice:'C', misconceptionId:'CI2' },
  { itemId:'FCI-10', choice:'D', misconceptionId:'CI2' },
  { itemId:'FCI-6',  choice:'A', misconceptionId:'CI3' },
  { itemId:'FCI-7',  choice:'B', misconceptionId:'CI3' },
  // FCI Centrifugal
  { itemId:'FCI-4',  choice:'C', misconceptionId:'CF' },
  { itemId:'FCI-4',  choice:'E', misconceptionId:'CF' },
  { itemId:'FCI-10', choice:'C', misconceptionId:'CF' },
  { itemId:'FCI-10', choice:'D', misconceptionId:'CF' },
  { itemId:'FCI-10', choice:'E', misconceptionId:'CF' },
  // FCI Obstacles
  { itemId:'FCI-2',  choice:'C', misconceptionId:'Ob' },
  { itemId:'FCI-9',  choice:'A', misconceptionId:'Ob' },
  { itemId:'FCI-9',  choice:'B', misconceptionId:'Ob' },
  { itemId:'FCI-12', choice:'A', misconceptionId:'Ob' },
  { itemId:'FCI-13', choice:'E', misconceptionId:'Ob' },
  { itemId:'FCI-14', choice:'E', misconceptionId:'Ob' },
  // FCI Gravity
  { itemId:'FCI-9',  choice:'A', misconceptionId:'G1' },
  { itemId:'FCI-12', choice:'C', misconceptionId:'G1' },
  { itemId:'FCI-5',  choice:'E', misconceptionId:'G2' },
  { itemId:'FCI-9',  choice:'E', misconceptionId:'G2' },
  { itemId:'FCI-1',  choice:'A', misconceptionId:'G3' },
  { itemId:'FCI-3',  choice:'B', misconceptionId:'G3' },
  { itemId:'FCI-3',  choice:'D', misconceptionId:'G3' },
  { itemId:'FCI-5',  choice:'B', misconceptionId:'G4' },
  { itemId:'FCI-17', choice:'B', misconceptionId:'G4' },
  { itemId:'FCI-5',  choice:'B', misconceptionId:'G5' },
  { itemId:'FCI-16', choice:'D', misconceptionId:'G5' },
];

/* ============================================================
   UPLOAD
   ============================================================ */
async function batchUpload(collectionName, items, idField) {
  const chunks = [];
  for (let i = 0; i < items.length; i += 400) chunks.push(items.slice(i, i + 400));
  for (const chunk of chunks) {
    const batch = db.batch();
    chunk.forEach(item => {
      const ref = idField ? db.collection(collectionName).doc(item[idField]) : db.collection(collectionName).doc();
      batch.set(ref, item);
    });
    await batch.commit();
  }
}

async function seed() {
  console.log('🌱 PhysiClinic Firestore 완전 시딩 시작...\n');

  console.log('1/7 📚 units...');
  await batchUpload('units', units, 'id');
  console.log(`    ✅ ${units.length}개`);

  console.log('2/7 📐 misconception_dimensions...');
  await batchUpload('misconception_dimensions', dims, 'id');
  console.log(`    ✅ ${dims.length}개`);

  console.log('3/7 🧠 misconceptions (전체 49개)...');
  await batchUpload('misconceptions', misconceptions, 'id');
  console.log(`    ✅ ${misconceptions.length}개`);

  console.log('4/7 📝 misconception_sentences...');
  await batchUpload('misconception_sentences', sentences, null);
  console.log(`    ✅ ${sentences.length}개`);

  console.log('5/7 🔑 scoring_keywords...');
  await batchUpload('scoring_keywords', keywords, null);
  console.log(`    ✅ ${keywords.length}개`);

  console.log('6/7 📋 fci_fmce_items (FMCE 43 + FCI 30)...');
  await batchUpload('fci_fmce_items', fciItems, 'id');
  console.log(`    ✅ ${fciItems.length}개`);

  console.log('7/7 🗺️  item_misconception_map...');
  await batchUpload('item_misconception_map', itemMap, null);
  console.log(`    ✅ ${itemMap.length}개`);

  console.log('\n🎉 시딩 완료!');
  console.log('   https://console.firebase.google.com → Firestore Database\n');
  console.log('   컬렉션          | 건수');
  console.log('   ─────────────────────────────');
  console.log(`   units                    | ${units.length}`);
  console.log(`   misconception_dimensions  | ${dims.length}`);
  console.log(`   misconceptions            | ${misconceptions.length}  ← unit1 K1~G5 + unit2/4 ME/WI/MD`);
  console.log(`   misconception_sentences   | ${sentences.length}`);
  console.log(`   scoring_keywords          | ${keywords.length}`);
  console.log(`   fci_fmce_items            | ${fciItems.length}  ← FMCE 43 + FCI 30`);
  console.log(`   item_misconception_map    | ${itemMap.length}`);
  process.exit(0);
}

seed().catch(err => {
  console.error('❌ 시딩 실패:', err.message);
  process.exit(1);
});
